/* ============================================================
   오답노트용 예문 데이터 — { 영단어: ["영어 예문", "한글 번역", "문법 설명"] }
   대표(빈출) 단어 위주. 여기 없는 단어는 game이 학습용 폴백 예문을 자동 생성.
   점진적으로 단어별 예문을 추가하면 그대로 오답노트에 반영됨.
   ============================================================ */
window.EXAMPLES = {
  "cat":["The cat is sleeping on the bed.","고양이가 침대에서 자고 있다.","현재진행형 'is + -ing'은 지금 하고 있는 동작을 나타냅니다."],
  "dog":["My dog likes to play in the park.","내 개는 공원에서 노는 걸 좋아한다.","주어가 3인칭 단수(My dog)라 동사에 -s가 붙어 'likes'. 'like to + 동사원형'은 ~하기를 좋아하다."],
  "sun":["The sun rises in the east.","해는 동쪽에서 뜬다.","변하지 않는 사실은 현재시제로 씁니다. 3인칭 단수라 'rises'."],
  "moon":["The moon is bright tonight.","오늘 밤 달이 밝다.","'be동사 + 형용사' 형태로 상태를 설명합니다(is bright)."],
  "star":["I can see many stars in the sky.","하늘에 많은 별이 보인다.","조동사 'can(~할 수 있다)' 뒤에는 항상 동사원형(see)이 옵니다."],
  "book":["She is reading an interesting book.","그녀는 재미있는 책을 읽고 있다.","현재진행형 'is + -ing'. 형용사 interesting이 명사 book을 꾸밉니다."],
  "fish":["We caught a big fish today.","우리는 오늘 큰 물고기를 잡았다.","과거시제. catch는 불규칙 동사로 과거형이 'caught'입니다."],
  "bird":["A bird is singing on the tree.","새가 나무 위에서 노래하고 있다.","현재진행형 'is + -ing'. 장소는 전치사 on으로 나타냅니다."],
  "tree":["There is a tall tree in the garden.","정원에 키 큰 나무가 있다.","'There is + 단수명사'는 '~가 있다'라는 존재를 나타냅니다."],
  "rain":["The rain stopped in the afternoon.","오후에 비가 그쳤다.","과거시제. 규칙 동사는 끝에 -ed를 붙입니다(stop→stopped, p 중복)."],
  "egg":["I eat two eggs every morning.","나는 매일 아침 계란 두 개를 먹는다.","반복되는 습관은 현재시제. 복수(two eggs)라 -s가 붙습니다."],
  "hand":["Please raise your hand.","손을 들어 주세요.","명령문은 동사원형으로 시작합니다. Please를 붙이면 공손해집니다."],
  "door":["Close the door, please.","문 좀 닫아 주세요.","동사원형으로 시작하는 명령문입니다."],
  "ball":["The children are playing with a ball.","아이들이 공을 가지고 놀고 있다.","주어가 복수(children)라 현재진행형이 'are + -ing'."],
  "king":["The king lived in a big castle.","왕은 큰 성에 살았다.","과거시제(live→lived). 'in + 장소'로 어디에 사는지 나타냅니다."],
  "milk":["I drink a glass of milk every day.","나는 매일 우유 한 잔을 마신다.","'a glass of ~'는 셀 수 없는 명사의 양을 세는 표현입니다."],
  "water":["Can I have a glass of water?","물 한 잔 주시겠어요?","'Can I ~?'는 허락·요청을 부드럽게 묻는 표현입니다."],
  "house":["They live in a small house.","그들은 작은 집에 산다.","현재시제. 주어가 복수(They)라 동사는 원형 그대로 live."],
  "car":["He drives his car to work.","그는 차를 몰고 출근한다.","3인칭 단수 주어(He)라 동사에 -s가 붙어 'drives'."],
  "bus":["I take the bus to school.","나는 버스를 타고 학교에 간다.","'take the bus'는 버스를 타다라는 관용 표현입니다."],
  "apple":["An apple a day keeps the doctor away.","하루 사과 한 개면 의사가 필요 없다.","유명한 속담. 모음 앞이라 'An', 3인칭 단수라 'keeps'."],
  "run":["I run every morning.","나는 매일 아침 달린다.","반복되는 습관은 현재시제로 표현합니다."],
  "eat":["Let's eat lunch together.","같이 점심 먹자.","'Let's + 동사원형'은 '~하자'라는 제안 표현입니다."],
  "go":["I go to school by bus.","나는 버스로 학교에 간다.","'by + 교통수단'은 ~을 타고라는 뜻(무관사)."],
  "come":["Please come to my party.","내 파티에 와 줘.","동사원형으로 시작하는 명령문. 방향은 전치사 to."],
  "see":["I can see the mountain from here.","여기서 산이 보인다.","조동사 can 뒤에는 동사원형(see). 'from ~'은 출발점."],
  "make":["She wants to make a cake.","그녀는 케이크를 만들고 싶어 한다.","'want to + 동사원형'은 ~하고 싶다. 3인칭 단수라 wants."],
  "take":["Take an umbrella with you.","우산을 가져가.","명령문. 'with you'는 '몸에 지니고'라는 뉘앙스를 더합니다."],
  "give":["Give me your hand.","손을 줘.","'give + 사람 + 사물'은 ~에게 …을 주다(4형식)."],
  "know":["I know the answer.","나는 답을 안다.","현재시제로 알고 있는 상태를 나타냅니다."],
  "want":["I want a cup of coffee.","나는 커피 한 잔을 원한다.","'a cup of ~'는 컵에 담긴 음료의 양을 세는 표현."],
  "need":["You need to rest.","너는 쉬어야 한다.","'need to + 동사원형'은 ~할 필요가 있다."],
  "help":["Can you help me?","나를 도와줄 수 있니?","'Can you ~?'는 상대에게 부탁·요청하는 표현입니다."],
  "walk":["We walk to the park every day.","우리는 매일 공원까지 걷는다.","현재시제 습관. 'to + 장소'는 목적지를 나타냅니다."],
  "jump":["The cat can jump very high.","그 고양이는 아주 높이 뛸 수 있다.","조동사 can + 동사원형. high는 동사를 꾸미는 부사."],
  "read":["I like to read books at night.","나는 밤에 책 읽는 걸 좋아한다.","'like to + 동사원형'. 'at night'은 밤에라는 시간 표현."],
  "write":["Please write your name here.","여기에 이름을 써 주세요.","명령문. here는 장소를 나타내는 부사입니다."],
  "sleep":["Babies sleep a lot.","아기들은 잠을 많이 잔다.","일반적 사실은 현재시제. 'a lot'은 '많이'라는 부사구."],
  "open":["Open the window, please.","창문 좀 열어 주세요.","동사원형으로 시작하는 명령문입니다."],
  "buy":["I want to buy a new phone.","나는 새 전화기를 사고 싶다.","'want to + 동사원형'. 형용사 new가 명사 phone을 꾸밉니다."],
  "meet":["Let's meet at six.","6시에 만나자.","'Let's + 동사원형'(제안). 'at + 시각'은 정확한 시간."],
  "play":["The kids play in the yard.","아이들이 마당에서 논다.","현재시제. 'in + 장소'로 어디서 노는지 나타냅니다."],
  "drink":["Drink more water.","물을 더 마셔.","명령문. more는 '더 많은'이라는 비교 표현입니다."],
  "sing":["She loves to sing.","그녀는 노래하는 걸 좋아한다.","'love to + 동사원형'. 3인칭 단수라 loves."],
  "dance":["They dance very well.","그들은 춤을 아주 잘 춘다.","well은 동사 dance를 꾸미는 부사(잘)입니다."],
  "learn":["I want to learn English.","나는 영어를 배우고 싶다.","'want to + 동사원형'은 ~하고 싶다."],
  "teach":["She teaches math at school.","그녀는 학교에서 수학을 가르친다.","3인칭 단수 주어라 -es가 붙어 'teaches'."],
  "study":["I study every evening.","나는 매일 저녁 공부한다.","반복되는 습관은 현재시제로 표현합니다."],
  "speak":["Can you speak English?","영어를 할 수 있나요?","'Can you ~?'로 능력·가능을 묻습니다."],
  "hear":["I can hear music.","음악이 들린다.","조동사 can + 동사원형(hear)."],
  "think":["I think you are right.","네 말이 맞는 것 같아.","'I think (that) + 문장'은 ~라고 생각하다. that은 생략 가능."],
  "like":["I like ice cream.","나는 아이스크림을 좋아한다.","현재시제로 좋아하는 상태를 나타냅니다."],
  "love":["I love my family.","나는 내 가족을 사랑한다.","현재시제. my는 소유격(나의)."],
  "hate":["I hate spiders.","나는 거미가 싫다.","일반적인 대상은 복수형(spiders)으로 씁니다."],
  "enjoy":["We enjoy playing soccer.","우리는 축구하는 걸 즐긴다.","enjoy 뒤에는 동명사(-ing)가 옵니다. 'to부정사'를 쓰지 않아요."],
  "start":["The movie starts at seven.","영화는 7시에 시작한다.","3인칭 단수라 starts. 'at + 시각'."],
  "finish":["I need to finish my homework.","나는 숙제를 끝내야 한다.","'need to + 동사원형'은 ~해야 한다."],
  "happy":["She looks very happy today.","그녀는 오늘 매우 행복해 보인다.","'look + 형용사'는 ~해 보이다. very는 형용사를 강조."],
  "big":["They live in a big city.","그들은 큰 도시에 산다.","형용사(big)가 명사(city) 앞에서 꾸며 줍니다."],
  "small":["I have a small dog.","나는 작은 개가 있다.","'have'는 가지고 있다. 형용사 small이 dog을 꾸밉니다."],
  "good":["This is a good idea.","이건 좋은 생각이야.","'be동사 + 형용사 + 명사' 구조입니다."],
  "bad":["The weather is bad today.","오늘 날씨가 나쁘다.","'be동사 + 형용사'로 상태를 설명합니다."],
  "hot":["The soup is very hot.","수프가 매우 뜨겁다.","very(매우)가 형용사 hot을 강조합니다."],
  "cold":["It is cold outside.","밖이 춥다.","날씨·상황을 말할 때 주어로 It을 씁니다(비인칭 it)."],
  "new":["I bought a new bike.","나는 새 자전거를 샀다.","과거시제. buy의 과거형은 불규칙형 'bought'."],
  "old":["This is an old book.","이건 오래된 책이다.","모음(o)으로 시작하는 단어 앞이라 'a'가 아니라 'an'."],
  "fast":["He is a fast runner.","그는 빠른 주자이다.","fast는 형용사로 명사 runner를 꾸밉니다."],
  "slow":["The turtle is very slow.","거북이는 매우 느리다.","'be + 형용사'. very로 정도를 강조합니다."],
  "long":["She has long hair.","그녀는 긴 머리를 가졌다.","3인칭 단수라 has. 형용사 long이 hair를 꾸밉니다."],
  "short":["He is short but strong.","그는 키가 작지만 힘이 세다.","but은 반대 내용을 잇는 접속사(그러나)."],
  "tall":["My brother is very tall.","내 형은 키가 매우 크다.","'be + 형용사'. very가 tall을 강조합니다."],
  "clean":["Please keep the room clean.","방을 깨끗하게 유지해 주세요.","'keep + 목적어 + 형용사'는 ~을 …한 상태로 유지하다(5형식)."],
  "tired":["I am very tired today.","나는 오늘 매우 피곤하다.","'be동사 + 형용사'. tired는 감정·상태 형용사."],
  "hungry":["I am hungry. Let's eat.","배고파. 먹자.","'be + 형용사'로 상태를, 'Let's + 동사원형'으로 제안을 합니다."],
  "angry":["Don't be angry with me.","나한테 화내지 마.","'Don't + 동사원형'은 부정 명령문(~하지 마)."],
  "friend":["She is my best friend.","그녀는 내 가장 친한 친구이다.","best는 good의 최상급(가장 좋은)."],
  "family":["I love spending time with my family.","나는 가족과 시간 보내는 걸 좋아한다.","'spend + 시간 + -ing'은 ~하며 시간을 보내다."],
  "school":["I go to school every day.","나는 매일 학교에 간다.","'go to school'은 등교하다라는 관용 표현(무관사)."],
  "mother":["My mother cooks delicious food.","우리 엄마는 맛있는 음식을 요리한다.","3인칭 단수 주어라 동사에 -s(cooks)."],
  "father":["My father works in an office.","우리 아빠는 사무실에서 일한다.","3인칭 단수라 works. 'in + 장소'."],
  "food":["Korean food is delicious.","한국 음식은 맛있다.","'be동사 + 형용사'로 맛·상태를 설명합니다."],
  "money":["I save money every month.","나는 매달 돈을 모은다.","현재시제 습관. money는 셀 수 없는 명사라 -s를 안 붙입니다."],
  "time":["What time is it now?","지금 몇 시야?","'What time is it?'은 시간을 묻는 정해진 표현입니다."],
  "work":["I work from nine to six.","나는 9시부터 6시까지 일한다.","'from A to B'는 A부터 B까지."],
  "home":["I want to go home.","나는 집에 가고 싶다.","'go home'은 집에 가다(home은 부사라 to가 없음)."],
  "night":["Good night! Sleep well.","잘 자! 푹 자.","명령문. well은 동사 sleep을 꾸미는 부사(잘)."],
  "day":["Have a nice day!","좋은 하루 보내!","동사원형으로 시작하는 명령문 형태의 인사말."],
  "name":["What is your name?","네 이름이 뭐야?","의문사 What으로 시작하는 의문문입니다."],
  "color":["What is your favorite color?","네가 가장 좋아하는 색이 뭐야?","의문사 의문문. favorite은 '가장 좋아하는'."],
  "foot":["My right foot hurts.","오른발이 아파요.","foot의 복수형은 feet(불규칙)이에요."],
  "bear":["A bear is sleeping in the cave.","곰이 동굴에서 자고 있어요.","현재진행형 'is + -ing'."],
  "cup":["Can I have a cup of tea?","차 한 잔 주시겠어요?","'a cup of ~'는 잔에 담긴 양을 세는 표현."],
  "pen":["Write it down with this pen.","이 펜으로 적어요.","'with + 도구'는 ~로(수단)."],
  "box":["Put the toys in the box.","장난감을 상자에 넣어요.","'in + 장소'는 ~안에."],
  "bed":["I go to bed at ten.","나는 10시에 잠자리에 들어요.","'go to bed'는 잠자리에들다(무관사)."],
  "hat":["He is wearing a red hat.","그는 빨간 모자를 쓰고 있어요.","wear는 입다·쓰다·착용하다."],
  "map":["Look at the map.","지도를 봐요.","명령문은 동사원형으로 시작해요."],
  "key":["I lost my car key.","차 열쇠를 잃어버렸어요.","과거시제(lose→lost, 불규칙)."],
  "bag":["This bag is too heavy.","이 가방은 너무 무거워요.","'too + 형용사'는 너무 ~한."],
  "cow":["The cow gives us milk.","소는 우리에게 우유를 줘요.","'give + 사람 + 사물'(4형식)."],
  "pig":["Pigs are pink and cute.","돼지는 분홍색이고 귀여워요.","복수 주어라 be동사는 are."],
  "ant":["An ant is very small.","개미는 아주 작아요.","모음 앞이라 부정관사 'an'."],
  "bee":["A bee is on the flower.","벌이 꽃 위에 있어요.","'on + 장소'는 ~위에."],
  "fox":["The fox runs very fast.","여우는 매우 빨리 달려요.","3인칭 단수라 runs."],
  "owl":["An owl sleeps in the day.","부엉이는 낮에 자요.","'in the day'는 낮에."],
  "leg":["My legs are tired.","다리가 피곤해요.","복수 legs라 be동사 are."],
  "eye":["Close your eyes.","눈을 감아요.","명령문. eyes는 eye의 복수."],
  "ear":["Rabbits have long ears.","토끼는 긴 귀를 가졌어요.","have는 가지고있다."],
  "lip":["Her lips are red.","그녀의 입술은 빨개요.","소유격 her(그녀의)."],
  "arm":["He has strong arms.","그는 튼튼한 팔을 가졌어요.","형용사 strong이 arms를 꾸며요."],
  "sky":["The sky is blue today.","오늘 하늘이 파래요.","'be + 형용사'로 상태를."],
  "sea":["We swim in the sea.","우리는 바다에서 수영해요.","'in the sea'는 바다에서."],
  "ice":["The ice is cold.","얼음은 차가워요.","ice는 셀 수 없는 명사."],
  "fire":["Be careful with fire.","불을 조심해요.","'be careful with ~'는 ~을 조심하다."],
  "wind":["The wind is strong.","바람이 세요.","'be + 형용사'."],
  "snow":["Children play in the snow.","아이들이 눈에서 놀아요.","snow는 셀 수 없는 명사."],
  "road":["Cross the road carefully.","길을 조심히 건너요.","carefully는 부사(조심히)."],
  "ship":["The ship sails on the sea.","배가 바다를 항해해요.","3인칭 단수 sails."],
  "wing":["Birds fly with their wings.","새는 날개로 날아요.","'with + 도구'."],
  "nose":["The dog has a wet nose.","개는 코가 촉촉해요.","형용사 wet이 nose를 꾸며요."],
  "rice":["I eat rice every day.","나는 매일 밥을 먹어요.","현재시제(습관)."],
  "hen":["The hen lays eggs.","암탉이 알을 낳아요.","3인칭 단수 lays."],
  "duck":["A duck swims in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'는 연못에서."],
  "goat":["The goat eats grass.","염소가 풀을 먹어요.","3인칭 단수 eats."],
  "lion":["The lion is the king of animals.","사자는 동물의 왕이에요.","'the king of ~'는 ~의 왕."],
  "tiger":["A tiger has stripes.","호랑이는 줄무늬가 있어요.","have/has는 가지고있다."],
  "zebra":["A zebra looks like a horse.","얼룩말은 말처럼 생겼어요.","'look like + 명사'는 ~처럼 보이다."],
  "wolf":["Wolves live in the forest.","늑대는 숲에 살아요.","wolf의 복수는 wolves(불규칙)."],
  "deer":["A deer ran into the woods.","사슴이 숲으로 뛰어 들어갔어요.","과거시제(run→ran)."],
  "frog":["The frog jumps high.","개구리가 높이 뛰어요.","high는 부사(높이)."],
  "sheep":["The sheep are in the field.","양들이 들판에 있어요.","sheep은 단수·복수 같은꼴."],
  "horse":["She rides a horse well.","그녀는 말을 잘 타요.","well은 부사(잘)."],
  "mouse":["A mouse is afraid of cats.","쥐는 고양이를 무서워해요.","'be afraid of ~'는 ~을 무서워하다."],
  "rabbit":["The rabbit has big ears.","토끼는 큰 귀를 가졌어요.","형용사 big이 ears를 꾸며요."],
  "snake":["A snake has no legs.","뱀은 다리가 없어요.","'have no ~'는 ~이 없다."],
  "crab":["The crab walks sideways.","게는 옆으로 걸어요.","sideways는 부사(옆으로)."],
  "shark":["A shark has sharp teeth.","상어는 날카로운 이빨이 있어요.","tooth의 복수는 teeth."],
  "whale":["The whale is the biggest animal.","고래는 가장 큰 동물이에요.","최상급 biggest."],
  "seal":["A seal can swim fast.","물개는 빨리 헤엄칠 수 있어요.","조동사 can + 동사원형."],
  "swan":["The swan is white and graceful.","백조는 하얗고 우아해요.","and로 형용사 두 개 연결."],
  "eagle":["An eagle flies high in the sky.","독수리가 하늘 높이 날아요.","high는 부사."],
  "dove":["A dove is a symbol of peace.","비둘기는 평화의 상징이에요.","'a symbol of ~'는 ~의 상징."],
  "crow":["The crow is black.","까마귀는 검어요.","'be + 형용사'."],
  "goose":["A goose has a long neck.","거위는 목이 길어요.","goose의 복수는 geese."],
  "panda":["The panda eats bamboo.","판다는 대나무를 먹어요.","3인칭 단수 eats."],
  "monkey":["Monkeys love bananas.","원숭이는 바나나를 좋아해요.","복수 주어라 love(원형)."],
  "camel":["A camel lives in the desert.","낙타는 사막에 살아요.","'in the desert'는 사막에서."],
  "kitten":["The kitten is so cute.","새끼고양이가 너무 귀여워요.","'so + 형용사'는 너무 ~한."],
  "puppy":["My puppy follows me everywhere.","내 강아지는 어디든 나를 따라와요.","everywhere는 부사(어디든)."],
  "chick":["The chick is yellow and small.","병아리는 노랗고 작아요.","and로 형용사 연결."],
  "lamb":["A lamb is a baby sheep.","새끼양은 아기 양이에요.","'A is B' 정의 문장."],
  "bull":["The bull is very strong.","황소는 매우 힘이 세요.","'very + 형용사'."],
  "bug":["There is a bug on the wall.","벽에 벌레가 있어요.","'There is + 단수'는 ~가 있다."],
  "worm":["The bird ate a worm.","새가 벌레를 먹었어요.","과거시제(eat→ate)."],
  "spider":["A spider has eight legs.","거미는 다리가 여덟 개예요.","수를 나타내는 eight."],
  "snail":["The snail moves very slowly.","달팽이는 아주 느리게 움직여요.","slowly는 부사(느리게)."],
  "turtle":["A turtle lives a long time.","거북이는 오래 살아요.","'a long time'은 오랫동안."],
  "shrimp":["I like fried shrimp.","나는 새우튀김을 좋아해요.","fried는 형용사(튀긴)."],
  "hippo":["The hippo stays in the water.","하마는 물 속에 머물러요.","'in the water'는 물 속에."],
  "rhino":["A rhino has a big horn.","코뿔소는 큰 뿔이 있어요.","형용사 big이 horn을 꾸며요."],
  "bat":["Bats fly at night.","박쥐는 밤에 날아요.","'at night'은 밤에."],
  "mole":["A mole digs under the ground.","두더지는 땅 밑을 파요.","'under the ground'는 땅 밑을."],
  "otter":["The otter swims in the river.","수달이 강에서 헤엄쳐요.","'in the river'는 강에서."],
  "beaver":["A beaver builds a dam.","비버는 댐을 지어요.","3인칭 단수 builds."],
  "squirrel":["The squirrel eats nuts.","다람쥐가 견과를 먹어요.","3인칭 단수 eats."],
  "ox":["An ox pulls the cart.","소가 수레를 끌어요.","ox의 복수는 oxen."],
  "head":["I have a headache in my head.","머리가 아파요.","headache는 두통."],
  "hair":["She has long black hair.","그녀는 길고 검은 머리를 가졌어요.","hair는 보통 셀 수 없는 명사."],
  "face":["Wash your face.","얼굴을 씻어요.","명령문."],
  "mouth":["Open your mouth.","입을 벌려요.","명령문."],
  "tooth":["Brush your teeth.","이를 닦아요.","tooth의 복수는 teeth."],
  "neck":["A giraffe has a long neck.","기린은 목이 길어요.","형용사 long이 neck을 꾸며요."],
  "back":["My back hurts.","등이 아파요.","back은 등·뒤."],
  "knee":["I hurt my knee.","무릎을 다쳤어요.","과거시제(hurt는 불규칙·동일형)."],
  "toe":["I have ten toes.","나는 발가락이 열 개예요.","수 ten."],
  "thumb":["He hurt his thumb.","그는 엄지를 다쳤어요.","소유격 his."],
  "chin":["She has a small chin.","그녀는 턱이 작아요.","형용사 small."],
  "cheek":["The baby has soft cheeks.","아기는 볼이 부드러워요.","형용사 soft."],
  "skin":["Babies have soft skin.","아기는 피부가 부드러워요.","skin은 셀 수 없는 명사."],
  "bone":["The dog likes bones.","개는 뼈를 좋아해요.","복수 bones."],
  "heart":["My heart beats fast.","심장이 빠르게 뛰어요.","fast는 부사."],
  "blood":["Blood is red.","피는 빨개요.","blood는 셀 수 없는 명사."],
  "chest":["He has a strong chest.","그는 가슴이 튼튼해요.","형용사 strong."],
  "heel":["My heel hurts.","발뒤꿈치가 아파요.","heel은 발뒤꿈치."],
  "palm":["She held it in her palm.","그녀는 손바닥에 그것을 쥐었어요.","과거시제(hold→held)."],
  "nail":["Cut your nails.","손톱을 깎아요.","명령문. nails 복수."],
  "wrist":["I wear a watch on my wrist.","나는 손목에 시계를 차요.","'on my wrist'는 손목에."],
  "brain":["The brain is very important.","뇌는 매우 중요해요.","'be + 형용사'."],
  "tongue":["Stick out your tongue.","혀를 내밀어요.","'stick out'은 내밀다."],
  "throat":["I have a sore throat.","목이 아파요.","sore는 형용사(아픈)."],
  "bread":["I eat bread for breakfast.","나는 아침으로 빵을 먹어요.","'for breakfast'는 아침으로."],
  "meat":["I don't eat meat.","나는 고기를 안 먹어요.","부정문 'don't + 동사원형'."],
  "soup":["The soup is hot.","수프가 뜨거워요.","'be + 형용사'."],
  "cake":["Let's make a cake.","케이크를 만들자.","'Let's + 동사원형'(제안)."],
  "ham":["I like ham and cheese.","나는 햄과 치즈를 좋아해요.","and로 명사 연결."],
  "corn":["Corn is yellow.","옥수수는 노래요.","corn은 셀 수 없는 명사."],
  "bean":["Beans are good for health.","콩은 건강에 좋아요.","'be good for ~'는 ~에 좋다."],
  "nut":["Squirrels eat nuts.","다람쥐는 견과를 먹어요.","복수 nuts."],
  "salt":["Add a little salt.","소금을 조금 넣어요.","'a little'은 약간(셀 수 없는 명사)."],
  "sugar":["I don't take sugar in my coffee.","나는 커피에 설탕을 안 넣어요.","부정문."],
  "oil":["Cook it in oil.","기름에 요리해요.","'in oil'은 기름에."],
  "tea":["Would you like some tea?","차 좀 드시겠어요?","'Would you like ~?'는 권유."],
  "juice":["I drink orange juice.","나는 오렌지 주스를 마셔요.","현재시제."],
  "beef":["This beef is delicious.","이 소고기는 맛있어요.","'be + 형용사'."],
  "pork":["We had pork for dinner.","우리는 저녁으로 돼지고기를 먹었어요.","과거시제(have→had)."],
  "fruit":["Eat more fruit.","과일을 더 먹어요.","more는 더 많은."],
  "grape":["Grapes are sweet.","포도는 달아요.","복수 grapes."],
  "peach":["This peach is juicy.","이 복숭아는 즙이 많아요.","형용사 juicy."],
  "pear":["A pear is bigger than an apple.","배는 사과보다 커요.","비교급 'bigger than'."],
  "plum":["The plum is purple.","자두는 보라색이에요.","'be + 형용사'."],
  "lemon":["A lemon is sour.","레몬은 셔요.","형용사 sour."],
  "melon":["This melon smells sweet.","이 멜론은 달콤한 냄새가 나요.","'smell + 형용사'는 ~한 냄새가 나다."],
  "berry":["Birds eat berries.","새는 베리를 먹어요.","berry의 복수는 berries."],
  "onion":["Onions make me cry.","양파는 나를 울려요.","'make + 목적어 + 동사원형'(5형식)."],
  "potato":["I like baked potatoes.","나는 구운 감자를 좋아해요.","potato의 복수는 potatoes."],
  "tomato":["A tomato is red and round.","토마토는 빨갛고 둥글어요.","and로 형용사 연결."],
  "carrot":["Rabbits love carrots.","토끼는 당근을 좋아해요.","복수 carrots."],
  "garlic":["Korean food uses a lot of garlic.","한국 음식은 마늘을 많이 써요.","'a lot of'는 많은."],
  "pepper":["Add some pepper.","후추를 좀 넣어요.","some은 약간의."],
  "candy":["Kids love candy.","아이들은 사탕을 좋아해요.","candy는 보통 셀 수 없는 명사."],
  "cookie":["I baked some cookies.","나는 쿠키를 좀 구웠어요.","과거시제 baked."],
  "honey":["Bees make honey.","벌은 꿀을 만들어요.","현재시제."],
  "butter":["Spread butter on the bread.","빵에 버터를 발라요.","'on the bread'는 빵에."],
  "cheese":["I like cheese on my pizza.","나는 피자에 치즈를 좋아해요.","'on my pizza'는 피자에."],
  "bacon":["I had bacon and eggs.","나는 베이컨과 달걀을 먹었어요.","과거시제 had."],
  "flour":["Mix the flour with water.","밀가루를 물과 섞어요.","'mix A with B'는 A를 B와 섞다."],
  "pasta":["I cooked pasta for dinner.","나는 저녁으로 파스타를 만들었어요.","과거시제 cooked."],
  "steak":["He likes his steak well-done.","그는 스테이크를 바싹 익힌 걸 좋아해요.","well-done은 바싹 익힌."],
  "donut":["I ate a chocolate donut.","나는 초콜릿 도넛을 먹었어요.","과거시제 ate."],
  "burger":["I ordered a cheese burger.","나는 치즈버거를 주문했어요.","과거시제 ordered."],
  "cream":["Add cream to the soup.","수프에 크림을 넣어요.","'add A to B'는 B에 A를 넣다."],
  "soda":["I drink too much soda.","나는 탄산음료를 너무 많이 마셔요.","'too much'는 너무 많은(셀 수 없는 명사)."],
  "salad":["I had a green salad.","나는 그린 샐러드를 먹었어요.","과거시제 had."],
  "snack":["Let's have a snack.","간식 먹자.","'have a snack'은 간식을 먹다."],
  "meal":["We had a big meal.","우리는 푸짐한 식사를 했어요.","형용사 big."],
  "kiwi":["A kiwi is green inside.","키위는 속이 초록색이에요.","inside는 부사(안쪽은)."],
  "mango":["Mangoes are sweet and soft.","망고는 달고 부드러워요.","mango의 복수는 mangoes."],
  "cloud":["There are white clouds in the sky.","하늘에 흰 구름이 있어요.","'There are + 복수'."],
  "wave":["The waves are big today.","오늘 파도가 커요.","복수 waves라 are."],
  "sand":["The sand is warm.","모래가 따뜻해요.","sand는 셀 수 없는 명사."],
  "rock":["He sat on a big rock.","그는 큰 바위에 앉았어요.","과거시제(sit→sat)."],
  "stone":["She threw a stone into the water.","그녀는 물에 돌을 던졌어요.","과거시제(throw→threw)."],
  "hill":["We walked up the hill.","우리는 언덕을 올라갔어요.","'up the hill'은 언덕 위로."],
  "lake":["We swam in the lake.","우리는 호수에서 수영했어요.","과거시제(swim→swam)."],
  "pond":["Ducks swim in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'."],
  "grass":["The grass is green.","잔디가 푸르러요.","grass는 셀 수 없는 명사."],
  "leaf":["The leaves fall in autumn.","가을에 잎이 떨어져요.","leaf의 복수는 leaves."],
  "seed":["Plant the seeds in spring.","봄에 씨앗을 심어요.","'in spring'은 봄에."],
  "wood":["The table is made of wood.","탁자는 나무로 만들어졌어요.","'be made of ~'는 ~로 만들어지다."],
  "gold":["This ring is made of gold.","이 반지는 금으로 만들어졌어요.","'be made of ~'."],
  "coal":["We burn coal for heat.","우리는 열을 위해 석탄을 태워요.","'for heat'은 열을 위해."],
  "mud":["The pig plays in the mud.","돼지가 진흙에서 놀아요.","'in the mud'는 진흙에서."],
  "dust":["There is dust on the shelf.","선반에 먼지가 있어요.","'There is + 셀 수 없는 명사'."],
  "fog":["The fog is thick this morning.","오늘 아침 안개가 짙어요.","형용사 thick."],
  "frost":["There was frost on the window.","창문에 서리가 끼었어요.","과거시제(there was)."],
  "flood":["The flood damaged the town.","홍수가 마을을 망가뜨렸어요.","과거시제 damaged."],
  "dawn":["We woke up at dawn.","우리는 새벽에 일어났어요.","'at dawn'은 새벽에."],
  "noon":["Let's meet at noon.","정오에 만나자.","'at noon'은 정오에."],
  "week":["I work five days a week.","나는 일주일에 닷새 일해요.","'a week'은 일주일에."],
  "year":["A year has twelve months.","일 년은 열두 달이에요.","숫자 twelve."],
  "month":["There are thirty days in a month.","한 달은 삼십 일이에요.","'in a month'는 한 달에."],
  "hole":["There is a hole in my sock.","내 양말에 구멍이 있어요.","'in my sock'은 양말에."],
  "cave":["Bats live in the cave.","박쥐는 동굴에 살아요.","'in the cave'."],
  "cliff":["Be careful near the cliff.","절벽 근처에서 조심해요.","'near the cliff'는 절벽 근처에서."],
  "shore":["We walked along the shore.","우리는 해안을 따라 걸었어요.","'along the shore'는 해안을 따라."],
  "coast":["The city is on the east coast.","그 도시는 동해안에 있어요.","'on the coast'는 해안에."],
  "branch":["A bird sat on the branch.","새가 나뭇가지에 앉았어요.","'on the branch'."],
  "bush":["A cat hid behind the bush.","고양이가 덤불 뒤에 숨었어요.","과거시제(hide→hid)."],
  "valley":["The river flows through the valley.","강이 계곡을 통해 흘러요.","'through the valley'는 계곡을 통해."],
  "desert":["It is very hot in the desert.","사막은 매우 더워요.","비인칭 주어 it."],
  "jungle":["Many animals live in the jungle.","많은 동물이 정글에 살아요.","'in the jungle'."],
  "swamp":["Crocodiles live in the swamp.","악어는 늪에 살아요.","'in the swamp'."]
};
