/* ============================================================
   오답노트용 예문 데이터 — { 영단어: ["영어 예문", "한글 번역", "문법 설명"] }
   대표(빈출) 단어 위주. 여기 없는 단어는 game이 학습용 폴백 예문을 자동 생성.
   점진적으로 단어별 예문을 추가하면 그대로 오답노트에 반영됨.
   ============================================================ */
window.EXAMPLES = {
  "cat":["The cat is sleeping on the bed.","고양이가 침대에서 자고 있다.","현재진행형 'is + -ing'은 지금 하고 있는 동작을 나타냅니다."],
  "dog":["My dog likes to play in the park.","내 개는 공원에서 노는 걸 좋아한다.","주어가 3인칭 단수(My dog)라 동사에 -s가 붙어 'likes'. 'like to + 동사원형'은 ~하기를 좋아하다."],
  "sun":["The sun rises in the east.","해는 동쪽에서 뜬다.","변하지 않는 사실은 현재시제로 씁니다. 3인칭 단수라 'rises'."],
  "moon":["The moon is bright tonight.","오늘 밤 달이 밝다.","'be동사 + 형용사' 형태로 상태를 설명합니다(is bright)."],
  "star":["I can see many stars in the sky.","하늘에 많은 별이 보인다.","조동사 'can(~할 수 있다)' 뒤에는 항상 동사원형(see)이 옵니다."],
  "book":["She is reading an interesting book.","그녀는 재미있는 책을 읽고 있다.","현재진행형 'is + -ing'. 형용사 interesting이 명사 book을 꾸밉니다."],
  "fish":["We caught a big fish today.","우리는 오늘 큰 물고기를 잡았다.","과거시제. catch는 불규칙 동사로 과거형이 'caught'입니다."],
  "bird":["A bird is singing on the tree.","새가 나무 위에서 노래하고 있다.","현재진행형 'is + -ing'. 장소는 전치사 on으로 나타냅니다."],
  "tree":["There is a tall tree in the garden.","정원에 키 큰 나무가 있다.","'There is + 단수명사'는 '~가 있다'라는 존재를 나타냅니다."],
  "rain":["The rain stopped in the afternoon.","오후에 비가 그쳤다.","과거시제. 규칙 동사는 끝에 -ed를 붙입니다(stop→stopped, p 중복)."],
  "egg":["I eat two eggs every morning.","나는 매일 아침 계란 두 개를 먹는다.","반복되는 습관은 현재시제. 복수(two eggs)라 -s가 붙습니다."],
  "hand":["Please raise your hand.","손을 들어 주세요.","명령문은 동사원형으로 시작합니다. Please를 붙이면 공손해집니다."],
  "door":["Close the door, please.","문 좀 닫아 주세요.","동사원형으로 시작하는 명령문입니다."],
  "ball":["The children are playing with a ball.","아이들이 공을 가지고 놀고 있다.","주어가 복수(children)라 현재진행형이 'are + -ing'."],
  "king":["The king lived in a big castle.","왕은 큰 성에 살았다.","과거시제(live→lived). 'in + 장소'로 어디에 사는지 나타냅니다."],
  "milk":["I drink a glass of milk every day.","나는 매일 우유 한 잔을 마신다.","'a glass of ~'는 셀 수 없는 명사의 양을 세는 표현입니다."],
  "water":["Can I have a glass of water?","물 한 잔 주시겠어요?","'Can I ~?'는 허락·요청을 부드럽게 묻는 표현입니다."],
  "house":["They live in a small house.","그들은 작은 집에 산다.","현재시제. 주어가 복수(They)라 동사는 원형 그대로 live."],
  "car":["He drives his car to work.","그는 차를 몰고 출근한다.","3인칭 단수 주어(He)라 동사에 -s가 붙어 'drives'."],
  "bus":["I take the bus to school.","나는 버스를 타고 학교에 간다.","'take the bus'는 버스를 타다라는 관용 표현입니다."],
  "apple":["An apple a day keeps the doctor away.","하루 사과 한 개면 의사가 필요 없다.","유명한 속담. 모음 앞이라 'An', 3인칭 단수라 'keeps'."],
  "run":["I run every morning.","나는 매일 아침 달린다.","반복되는 습관은 현재시제로 표현합니다."],
  "eat":["Let's eat lunch together.","같이 점심 먹자.","'Let's + 동사원형'은 '~하자'라는 제안 표현입니다."],
  "go":["I go to school by bus.","나는 버스로 학교에 간다.","'by + 교통수단'은 ~을 타고라는 뜻(무관사)."],
  "come":["Please come to my party.","내 파티에 와 줘.","동사원형으로 시작하는 명령문. 방향은 전치사 to."],
  "see":["I can see the mountain from here.","여기서 산이 보인다.","조동사 can 뒤에는 동사원형(see). 'from ~'은 출발점."],
  "make":["She wants to make a cake.","그녀는 케이크를 만들고 싶어 한다.","'want to + 동사원형'은 ~하고 싶다. 3인칭 단수라 wants."],
  "take":["Take an umbrella with you.","우산을 가져가.","명령문. 'with you'는 '몸에 지니고'라는 뉘앙스를 더합니다."],
  "give":["Give me your hand.","손을 줘.","'give + 사람 + 사물'은 ~에게 …을 주다(4형식)."],
  "know":["I know the answer.","나는 답을 안다.","현재시제로 알고 있는 상태를 나타냅니다."],
  "want":["I want a cup of coffee.","나는 커피 한 잔을 원한다.","'a cup of ~'는 컵에 담긴 음료의 양을 세는 표현."],
  "need":["You need to rest.","너는 쉬어야 한다.","'need to + 동사원형'은 ~할 필요가 있다."],
  "help":["Can you help me?","나를 도와줄 수 있니?","'Can you ~?'는 상대에게 부탁·요청하는 표현입니다."],
  "walk":["We walk to the park every day.","우리는 매일 공원까지 걷는다.","현재시제 습관. 'to + 장소'는 목적지를 나타냅니다."],
  "jump":["The cat can jump very high.","그 고양이는 아주 높이 뛸 수 있다.","조동사 can + 동사원형. high는 동사를 꾸미는 부사."],
  "read":["I like to read books at night.","나는 밤에 책 읽는 걸 좋아한다.","'like to + 동사원형'. 'at night'은 밤에라는 시간 표현."],
  "write":["Please write your name here.","여기에 이름을 써 주세요.","명령문. here는 장소를 나타내는 부사입니다."],
  "sleep":["Babies sleep a lot.","아기들은 잠을 많이 잔다.","일반적 사실은 현재시제. 'a lot'은 '많이'라는 부사구."],
  "open":["Open the window, please.","창문 좀 열어 주세요.","동사원형으로 시작하는 명령문입니다."],
  "buy":["I want to buy a new phone.","나는 새 전화기를 사고 싶다.","'want to + 동사원형'. 형용사 new가 명사 phone을 꾸밉니다."],
  "meet":["Let's meet at six.","6시에 만나자.","'Let's + 동사원형'(제안). 'at + 시각'은 정확한 시간."],
  "play":["The kids play in the yard.","아이들이 마당에서 논다.","현재시제. 'in + 장소'로 어디서 노는지 나타냅니다."],
  "drink":["Drink more water.","물을 더 마셔.","명령문. more는 '더 많은'이라는 비교 표현입니다."],
  "sing":["She loves to sing.","그녀는 노래하는 걸 좋아한다.","'love to + 동사원형'. 3인칭 단수라 loves."],
  "dance":["They dance very well.","그들은 춤을 아주 잘 춘다.","well은 동사 dance를 꾸미는 부사(잘)입니다."],
  "learn":["I want to learn English.","나는 영어를 배우고 싶다.","'want to + 동사원형'은 ~하고 싶다."],
  "teach":["She teaches math at school.","그녀는 학교에서 수학을 가르친다.","3인칭 단수 주어라 -es가 붙어 'teaches'."],
  "study":["I study every evening.","나는 매일 저녁 공부한다.","반복되는 습관은 현재시제로 표현합니다."],
  "speak":["Can you speak English?","영어를 할 수 있나요?","'Can you ~?'로 능력·가능을 묻습니다."],
  "hear":["I can hear music.","음악이 들린다.","조동사 can + 동사원형(hear)."],
  "think":["I think you are right.","네 말이 맞는 것 같아.","'I think (that) + 문장'은 ~라고 생각하다. that은 생략 가능."],
  "like":["I like ice cream.","나는 아이스크림을 좋아한다.","현재시제로 좋아하는 상태를 나타냅니다."],
  "love":["I love my family.","나는 내 가족을 사랑한다.","현재시제. my는 소유격(나의)."],
  "hate":["I hate spiders.","나는 거미가 싫다.","일반적인 대상은 복수형(spiders)으로 씁니다."],
  "enjoy":["We enjoy playing soccer.","우리는 축구하는 걸 즐긴다.","enjoy 뒤에는 동명사(-ing)가 옵니다. 'to부정사'를 쓰지 않아요."],
  "start":["The movie starts at seven.","영화는 7시에 시작한다.","3인칭 단수라 starts. 'at + 시각'."],
  "finish":["I need to finish my homework.","나는 숙제를 끝내야 한다.","'need to + 동사원형'은 ~해야 한다."],
  "happy":["She looks very happy today.","그녀는 오늘 매우 행복해 보인다.","'look + 형용사'는 ~해 보이다. very는 형용사를 강조."],
  "big":["They live in a big city.","그들은 큰 도시에 산다.","형용사(big)가 명사(city) 앞에서 꾸며 줍니다."],
  "small":["I have a small dog.","나는 작은 개가 있다.","'have'는 가지고 있다. 형용사 small이 dog을 꾸밉니다."],
  "good":["This is a good idea.","이건 좋은 생각이야.","'be동사 + 형용사 + 명사' 구조입니다."],
  "bad":["The weather is bad today.","오늘 날씨가 나쁘다.","'be동사 + 형용사'로 상태를 설명합니다."],
  "hot":["The soup is very hot.","수프가 매우 뜨겁다.","very(매우)가 형용사 hot을 강조합니다."],
  "cold":["It is cold outside.","밖이 춥다.","날씨·상황을 말할 때 주어로 It을 씁니다(비인칭 it)."],
  "new":["I bought a new bike.","나는 새 자전거를 샀다.","과거시제. buy의 과거형은 불규칙형 'bought'."],
  "old":["This is an old book.","이건 오래된 책이다.","모음(o)으로 시작하는 단어 앞이라 'a'가 아니라 'an'."],
  "fast":["He is a fast runner.","그는 빠른 주자이다.","fast는 형용사로 명사 runner를 꾸밉니다."],
  "slow":["The turtle is very slow.","거북이는 매우 느리다.","'be + 형용사'. very로 정도를 강조합니다."],
  "long":["She has long hair.","그녀는 긴 머리를 가졌다.","3인칭 단수라 has. 형용사 long이 hair를 꾸밉니다."],
  "short":["He is short but strong.","그는 키가 작지만 힘이 세다.","but은 반대 내용을 잇는 접속사(그러나)."],
  "tall":["My brother is very tall.","내 형은 키가 매우 크다.","'be + 형용사'. very가 tall을 강조합니다."],
  "clean":["Please keep the room clean.","방을 깨끗하게 유지해 주세요.","'keep + 목적어 + 형용사'는 ~을 …한 상태로 유지하다(5형식)."],
  "tired":["I am very tired today.","나는 오늘 매우 피곤하다.","'be동사 + 형용사'. tired는 감정·상태 형용사."],
  "hungry":["I am hungry. Let's eat.","배고파. 먹자.","'be + 형용사'로 상태를, 'Let's + 동사원형'으로 제안을 합니다."],
  "angry":["Don't be angry with me.","나한테 화내지 마.","'Don't + 동사원형'은 부정 명령문(~하지 마)."],
  "friend":["She is my best friend.","그녀는 내 가장 친한 친구이다.","best는 good의 최상급(가장 좋은)."],
  "family":["I love spending time with my family.","나는 가족과 시간 보내는 걸 좋아한다.","'spend + 시간 + -ing'은 ~하며 시간을 보내다."],
  "school":["I go to school every day.","나는 매일 학교에 간다.","'go to school'은 등교하다라는 관용 표현(무관사)."],
  "mother":["My mother cooks delicious food.","우리 엄마는 맛있는 음식을 요리한다.","3인칭 단수 주어라 동사에 -s(cooks)."],
  "father":["My father works in an office.","우리 아빠는 사무실에서 일한다.","3인칭 단수라 works. 'in + 장소'."],
  "food":["Korean food is delicious.","한국 음식은 맛있다.","'be동사 + 형용사'로 맛·상태를 설명합니다."],
  "money":["I save money every month.","나는 매달 돈을 모은다.","현재시제 습관. money는 셀 수 없는 명사라 -s를 안 붙입니다."],
  "time":["What time is it now?","지금 몇 시야?","'What time is it?'은 시간을 묻는 정해진 표현입니다."],
  "work":["I work from nine to six.","나는 9시부터 6시까지 일한다.","'from A to B'는 A부터 B까지."],
  "home":["I want to go home.","나는 집에 가고 싶다.","'go home'은 집에 가다(home은 부사라 to가 없음)."],
  "night":["Good night! Sleep well.","잘 자! 푹 자.","명령문. well은 동사 sleep을 꾸미는 부사(잘)."],
  "day":["Have a nice day!","좋은 하루 보내!","동사원형으로 시작하는 명령문 형태의 인사말."],
  "name":["What is your name?","네 이름이 뭐야?","의문사 What으로 시작하는 의문문입니다."],
  "color":["What is your favorite color?","네가 가장 좋아하는 색이 뭐야?","의문사 의문문. favorite은 '가장 좋아하는'."],
  "foot":["My right foot hurts.","오른발이 아파요.","foot의 복수형은 feet(불규칙)이에요."],
  "bear":["A bear is sleeping in the cave.","곰이 동굴에서 자고 있어요.","현재진행형 'is + -ing'."],
  "cup":["Can I have a cup of tea?","차 한 잔 주시겠어요?","'a cup of ~'는 잔에 담긴 양을 세는 표현."],
  "pen":["Write it down with this pen.","이 펜으로 적어요.","'with + 도구'는 ~로(수단)."],
  "box":["Put the toys in the box.","장난감을 상자에 넣어요.","'in + 장소'는 ~안에."],
  "bed":["I go to bed at ten.","나는 10시에 잠자리에 들어요.","'go to bed'는 잠자리에들다(무관사)."],
  "hat":["He is wearing a red hat.","그는 빨간 모자를 쓰고 있어요.","wear는 입다·쓰다·착용하다."],
  "map":["Look at the map.","지도를 봐요.","명령문은 동사원형으로 시작해요."],
  "key":["I lost my car key.","차 열쇠를 잃어버렸어요.","과거시제(lose→lost, 불규칙)."],
  "bag":["This bag is too heavy.","이 가방은 너무 무거워요.","'too + 형용사'는 너무 ~한."],
  "cow":["The cow gives us milk.","소는 우리에게 우유를 줘요.","'give + 사람 + 사물'(4형식)."],
  "pig":["Pigs are pink and cute.","돼지는 분홍색이고 귀여워요.","복수 주어라 be동사는 are."],
  "ant":["An ant is very small.","개미는 아주 작아요.","모음 앞이라 부정관사 'an'."],
  "bee":["A bee is on the flower.","벌이 꽃 위에 있어요.","'on + 장소'는 ~위에."],
  "fox":["The fox runs very fast.","여우는 매우 빨리 달려요.","3인칭 단수라 runs."],
  "owl":["An owl sleeps in the day.","부엉이는 낮에 자요.","'in the day'는 낮에."],
  "leg":["My legs are tired.","다리가 피곤해요.","복수 legs라 be동사 are."],
  "eye":["Close your eyes.","눈을 감아요.","명령문. eyes는 eye의 복수."],
  "ear":["Rabbits have long ears.","토끼는 긴 귀를 가졌어요.","have는 가지고있다."],
  "lip":["Her lips are red.","그녀의 입술은 빨개요.","소유격 her(그녀의)."],
  "arm":["He has strong arms.","그는 튼튼한 팔을 가졌어요.","형용사 strong이 arms를 꾸며요."],
  "sky":["The sky is blue today.","오늘 하늘이 파래요.","'be + 형용사'로 상태를."],
  "sea":["We swim in the sea.","우리는 바다에서 수영해요.","'in the sea'는 바다에서."],
  "ice":["The ice is cold.","얼음은 차가워요.","ice는 셀 수 없는 명사."],
  "fire":["Be careful with fire.","불을 조심해요.","'be careful with ~'는 ~을 조심하다."],
  "wind":["The wind is strong.","바람이 세요.","'be + 형용사'."],
  "snow":["Children play in the snow.","아이들이 눈에서 놀아요.","snow는 셀 수 없는 명사."],
  "road":["Cross the road carefully.","길을 조심히 건너요.","carefully는 부사(조심히)."],
  "ship":["The ship sails on the sea.","배가 바다를 항해해요.","3인칭 단수 sails."],
  "wing":["Birds fly with their wings.","새는 날개로 날아요.","'with + 도구'."],
  "nose":["The dog has a wet nose.","개는 코가 촉촉해요.","형용사 wet이 nose를 꾸며요."],
  "rice":["I eat rice every day.","나는 매일 밥을 먹어요.","현재시제(습관)."],
  "hen":["The hen lays eggs.","암탉이 알을 낳아요.","3인칭 단수 lays."],
  "duck":["A duck swims in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'는 연못에서."],
  "goat":["The goat eats grass.","염소가 풀을 먹어요.","3인칭 단수 eats."],
  "lion":["The lion is the king of animals.","사자는 동물의 왕이에요.","'the king of ~'는 ~의 왕."],
  "tiger":["A tiger has stripes.","호랑이는 줄무늬가 있어요.","have/has는 가지고있다."],
  "zebra":["A zebra looks like a horse.","얼룩말은 말처럼 생겼어요.","'look like + 명사'는 ~처럼 보이다."],
  "wolf":["Wolves live in the forest.","늑대는 숲에 살아요.","wolf의 복수는 wolves(불규칙)."],
  "deer":["A deer ran into the woods.","사슴이 숲으로 뛰어 들어갔어요.","과거시제(run→ran)."],
  "frog":["The frog jumps high.","개구리가 높이 뛰어요.","high는 부사(높이)."],
  "sheep":["The sheep are in the field.","양들이 들판에 있어요.","sheep은 단수·복수 같은꼴."],
  "horse":["She rides a horse well.","그녀는 말을 잘 타요.","well은 부사(잘)."],
  "mouse":["A mouse is afraid of cats.","쥐는 고양이를 무서워해요.","'be afraid of ~'는 ~을 무서워하다."],
  "rabbit":["The rabbit has big ears.","토끼는 큰 귀를 가졌어요.","형용사 big이 ears를 꾸며요."],
  "snake":["A snake has no legs.","뱀은 다리가 없어요.","'have no ~'는 ~이 없다."],
  "crab":["The crab walks sideways.","게는 옆으로 걸어요.","sideways는 부사(옆으로)."],
  "shark":["A shark has sharp teeth.","상어는 날카로운 이빨이 있어요.","tooth의 복수는 teeth."],
  "whale":["The whale is the biggest animal.","고래는 가장 큰 동물이에요.","최상급 biggest."],
  "seal":["A seal can swim fast.","물개는 빨리 헤엄칠 수 있어요.","조동사 can + 동사원형."],
  "swan":["The swan is white and graceful.","백조는 하얗고 우아해요.","and로 형용사 두 개 연결."],
  "eagle":["An eagle flies high in the sky.","독수리가 하늘 높이 날아요.","high는 부사."],
  "dove":["A dove is a symbol of peace.","비둘기는 평화의 상징이에요.","'a symbol of ~'는 ~의 상징."],
  "crow":["The crow is black.","까마귀는 검어요.","'be + 형용사'."],
  "goose":["A goose has a long neck.","거위는 목이 길어요.","goose의 복수는 geese."],
  "panda":["The panda eats bamboo.","판다는 대나무를 먹어요.","3인칭 단수 eats."],
  "monkey":["Monkeys love bananas.","원숭이는 바나나를 좋아해요.","복수 주어라 love(원형)."],
  "camel":["A camel lives in the desert.","낙타는 사막에 살아요.","'in the desert'는 사막에서."],
  "kitten":["The kitten is so cute.","새끼고양이가 너무 귀여워요.","'so + 형용사'는 너무 ~한."],
  "puppy":["My puppy follows me everywhere.","내 강아지는 어디든 나를 따라와요.","everywhere는 부사(어디든)."],
  "chick":["The chick is yellow and small.","병아리는 노랗고 작아요.","and로 형용사 연결."],
  "lamb":["A lamb is a baby sheep.","새끼양은 아기 양이에요.","'A is B' 정의 문장."],
  "bull":["The bull is very strong.","황소는 매우 힘이 세요.","'very + 형용사'."],
  "bug":["There is a bug on the wall.","벽에 벌레가 있어요.","'There is + 단수'는 ~가 있다."],
  "worm":["The bird ate a worm.","새가 벌레를 먹었어요.","과거시제(eat→ate)."],
  "spider":["A spider has eight legs.","거미는 다리가 여덟 개예요.","수를 나타내는 eight."],
  "snail":["The snail moves very slowly.","달팽이는 아주 느리게 움직여요.","slowly는 부사(느리게)."],
  "turtle":["A turtle lives a long time.","거북이는 오래 살아요.","'a long time'은 오랫동안."],
  "shrimp":["I like fried shrimp.","나는 새우튀김을 좋아해요.","fried는 형용사(튀긴)."],
  "hippo":["The hippo stays in the water.","하마는 물 속에 머물러요.","'in the water'는 물 속에."],
  "rhino":["A rhino has a big horn.","코뿔소는 큰 뿔이 있어요.","형용사 big이 horn을 꾸며요."],
  "bat":["Bats fly at night.","박쥐는 밤에 날아요.","'at night'은 밤에."],
  "mole":["A mole digs under the ground.","두더지는 땅 밑을 파요.","'under the ground'는 땅 밑을."],
  "otter":["The otter swims in the river.","수달이 강에서 헤엄쳐요.","'in the river'는 강에서."],
  "beaver":["A beaver builds a dam.","비버는 댐을 지어요.","3인칭 단수 builds."],
  "squirrel":["The squirrel eats nuts.","다람쥐가 견과를 먹어요.","3인칭 단수 eats."],
  "ox":["An ox pulls the cart.","소가 수레를 끌어요.","ox의 복수는 oxen."],
  "head":["I have a headache in my head.","머리가 아파요.","headache는 두통."],
  "hair":["She has long black hair.","그녀는 길고 검은 머리를 가졌어요.","hair는 보통 셀 수 없는 명사."],
  "face":["Wash your face.","얼굴을 씻어요.","명령문."],
  "mouth":["Open your mouth.","입을 벌려요.","명령문."],
  "tooth":["Brush your teeth.","이를 닦아요.","tooth의 복수는 teeth."],
  "neck":["A giraffe has a long neck.","기린은 목이 길어요.","형용사 long이 neck을 꾸며요."],
  "back":["My back hurts.","등이 아파요.","back은 등·뒤."],
  "knee":["I hurt my knee.","무릎을 다쳤어요.","과거시제(hurt는 불규칙·동일형)."],
  "toe":["I have ten toes.","나는 발가락이 열 개예요.","수 ten."],
  "thumb":["He hurt his thumb.","그는 엄지를 다쳤어요.","소유격 his."],
  "chin":["She has a small chin.","그녀는 턱이 작아요.","형용사 small."],
  "cheek":["The baby has soft cheeks.","아기는 볼이 부드러워요.","형용사 soft."],
  "skin":["Babies have soft skin.","아기는 피부가 부드러워요.","skin은 셀 수 없는 명사."],
  "bone":["The dog likes bones.","개는 뼈를 좋아해요.","복수 bones."],
  "heart":["My heart beats fast.","심장이 빠르게 뛰어요.","fast는 부사."],
  "blood":["Blood is red.","피는 빨개요.","blood는 셀 수 없는 명사."],
  "chest":["He has a strong chest.","그는 가슴이 튼튼해요.","형용사 strong."],
  "heel":["My heel hurts.","발뒤꿈치가 아파요.","heel은 발뒤꿈치."],
  "palm":["She held it in her palm.","그녀는 손바닥에 그것을 쥐었어요.","과거시제(hold→held)."],
  "nail":["Cut your nails.","손톱을 깎아요.","명령문. nails 복수."],
  "wrist":["I wear a watch on my wrist.","나는 손목에 시계를 차요.","'on my wrist'는 손목에."],
  "brain":["The brain is very important.","뇌는 매우 중요해요.","'be + 형용사'."],
  "tongue":["Stick out your tongue.","혀를 내밀어요.","'stick out'은 내밀다."],
  "throat":["I have a sore throat.","목이 아파요.","sore는 형용사(아픈)."],
  "bread":["I eat bread for breakfast.","나는 아침으로 빵을 먹어요.","'for breakfast'는 아침으로."],
  "meat":["I don't eat meat.","나는 고기를 안 먹어요.","부정문 'don't + 동사원형'."],
  "soup":["The soup is hot.","수프가 뜨거워요.","'be + 형용사'."],
  "cake":["Let's make a cake.","케이크를 만들자.","'Let's + 동사원형'(제안)."],
  "ham":["I like ham and cheese.","나는 햄과 치즈를 좋아해요.","and로 명사 연결."],
  "corn":["Corn is yellow.","옥수수는 노래요.","corn은 셀 수 없는 명사."],
  "bean":["Beans are good for health.","콩은 건강에 좋아요.","'be good for ~'는 ~에 좋다."],
  "nut":["Squirrels eat nuts.","다람쥐는 견과를 먹어요.","복수 nuts."],
  "salt":["Add a little salt.","소금을 조금 넣어요.","'a little'은 약간(셀 수 없는 명사)."],
  "sugar":["I don't take sugar in my coffee.","나는 커피에 설탕을 안 넣어요.","부정문."],
  "oil":["Cook it in oil.","기름에 요리해요.","'in oil'은 기름에."],
  "tea":["Would you like some tea?","차 좀 드시겠어요?","'Would you like ~?'는 권유."],
  "juice":["I drink orange juice.","나는 오렌지 주스를 마셔요.","현재시제."],
  "beef":["This beef is delicious.","이 소고기는 맛있어요.","'be + 형용사'."],
  "pork":["We had pork for dinner.","우리는 저녁으로 돼지고기를 먹었어요.","과거시제(have→had)."],
  "fruit":["Eat more fruit.","과일을 더 먹어요.","more는 더 많은."],
  "grape":["Grapes are sweet.","포도는 달아요.","복수 grapes."],
  "peach":["This peach is juicy.","이 복숭아는 즙이 많아요.","형용사 juicy."],
  "pear":["A pear is bigger than an apple.","배는 사과보다 커요.","비교급 'bigger than'."],
  "plum":["The plum is purple.","자두는 보라색이에요.","'be + 형용사'."],
  "lemon":["A lemon is sour.","레몬은 셔요.","형용사 sour."],
  "melon":["This melon smells sweet.","이 멜론은 달콤한 냄새가 나요.","'smell + 형용사'는 ~한 냄새가 나다."],
  "berry":["Birds eat berries.","새는 베리를 먹어요.","berry의 복수는 berries."],
  "onion":["Onions make me cry.","양파는 나를 울려요.","'make + 목적어 + 동사원형'(5형식)."],
  "potato":["I like baked potatoes.","나는 구운 감자를 좋아해요.","potato의 복수는 potatoes."],
  "tomato":["A tomato is red and round.","토마토는 빨갛고 둥글어요.","and로 형용사 연결."],
  "carrot":["Rabbits love carrots.","토끼는 당근을 좋아해요.","복수 carrots."],
  "garlic":["Korean food uses a lot of garlic.","한국 음식은 마늘을 많이 써요.","'a lot of'는 많은."],
  "pepper":["Add some pepper.","후추를 좀 넣어요.","some은 약간의."],
  "candy":["Kids love candy.","아이들은 사탕을 좋아해요.","candy는 보통 셀 수 없는 명사."],
  "cookie":["I baked some cookies.","나는 쿠키를 좀 구웠어요.","과거시제 baked."],
  "honey":["Bees make honey.","벌은 꿀을 만들어요.","현재시제."],
  "butter":["Spread butter on the bread.","빵에 버터를 발라요.","'on the bread'는 빵에."],
  "cheese":["I like cheese on my pizza.","나는 피자에 치즈를 좋아해요.","'on my pizza'는 피자에."],
  "bacon":["I had bacon and eggs.","나는 베이컨과 달걀을 먹었어요.","과거시제 had."],
  "flour":["Mix the flour with water.","밀가루를 물과 섞어요.","'mix A with B'는 A를 B와 섞다."],
  "pasta":["I cooked pasta for dinner.","나는 저녁으로 파스타를 만들었어요.","과거시제 cooked."],
  "steak":["He likes his steak well-done.","그는 스테이크를 바싹 익힌 걸 좋아해요.","well-done은 바싹 익힌."],
  "donut":["I ate a chocolate donut.","나는 초콜릿 도넛을 먹었어요.","과거시제 ate."],
  "burger":["I ordered a cheese burger.","나는 치즈버거를 주문했어요.","과거시제 ordered."],
  "cream":["Add cream to the soup.","수프에 크림을 넣어요.","'add A to B'는 B에 A를 넣다."],
  "soda":["I drink too much soda.","나는 탄산음료를 너무 많이 마셔요.","'too much'는 너무 많은(셀 수 없는 명사)."],
  "salad":["I had a green salad.","나는 그린 샐러드를 먹었어요.","과거시제 had."],
  "snack":["Let's have a snack.","간식 먹자.","'have a snack'은 간식을 먹다."],
  "meal":["We had a big meal.","우리는 푸짐한 식사를 했어요.","형용사 big."],
  "kiwi":["A kiwi is green inside.","키위는 속이 초록색이에요.","inside는 부사(안쪽은)."],
  "mango":["Mangoes are sweet and soft.","망고는 달고 부드러워요.","mango의 복수는 mangoes."],
  "cloud":["There are white clouds in the sky.","하늘에 흰 구름이 있어요.","'There are + 복수'."],
  "wave":["The waves are big today.","오늘 파도가 커요.","복수 waves라 are."],
  "sand":["The sand is warm.","모래가 따뜻해요.","sand는 셀 수 없는 명사."],
  "rock":["He sat on a big rock.","그는 큰 바위에 앉았어요.","과거시제(sit→sat)."],
  "stone":["She threw a stone into the water.","그녀는 물에 돌을 던졌어요.","과거시제(throw→threw)."],
  "hill":["We walked up the hill.","우리는 언덕을 올라갔어요.","'up the hill'은 언덕 위로."],
  "lake":["We swam in the lake.","우리는 호수에서 수영했어요.","과거시제(swim→swam)."],
  "pond":["Ducks swim in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'."],
  "grass":["The grass is green.","잔디가 푸르러요.","grass는 셀 수 없는 명사."],
  "leaf":["The leaves fall in autumn.","가을에 잎이 떨어져요.","leaf의 복수는 leaves."],
  "seed":["Plant the seeds in spring.","봄에 씨앗을 심어요.","'in spring'은 봄에."],
  "wood":["The table is made of wood.","탁자는 나무로 만들어졌어요.","'be made of ~'는 ~로 만들어지다."],
  "gold":["This ring is made of gold.","이 반지는 금으로 만들어졌어요.","'be made of ~'."],
  "coal":["We burn coal for heat.","우리는 열을 위해 석탄을 태워요.","'for heat'은 열을 위해."],
  "mud":["The pig plays in the mud.","돼지가 진흙에서 놀아요.","'in the mud'는 진흙에서."],
  "dust":["There is dust on the shelf.","선반에 먼지가 있어요.","'There is + 셀 수 없는 명사'."],
  "fog":["The fog is thick this morning.","오늘 아침 안개가 짙어요.","형용사 thick."],
  "frost":["There was frost on the window.","창문에 서리가 끼었어요.","과거시제(there was)."],
  "flood":["The flood damaged the town.","홍수가 마을을 망가뜨렸어요.","과거시제 damaged."],
  "dawn":["We woke up at dawn.","우리는 새벽에 일어났어요.","'at dawn'은 새벽에."],
  "noon":["Let's meet at noon.","정오에 만나자.","'at noon'은 정오에."],
  "week":["I work five days a week.","나는 일주일에 닷새 일해요.","'a week'은 일주일에."],
  "year":["A year has twelve months.","일 년은 열두 달이에요.","숫자 twelve."],
  "month":["There are thirty days in a month.","한 달은 삼십 일이에요.","'in a month'는 한 달에."],
  "hole":["There is a hole in my sock.","내 양말에 구멍이 있어요.","'in my sock'은 양말에."],
  "cave":["Bats live in the cave.","박쥐는 동굴에 살아요.","'in the cave'."],
  "cliff":["Be careful near the cliff.","절벽 근처에서 조심해요.","'near the cliff'는 절벽 근처에서."],
  "shore":["We walked along the shore.","우리는 해안을 따라 걸었어요.","'along the shore'는 해안을 따라."],
  "coast":["The city is on the east coast.","그 도시는 동해안에 있어요.","'on the coast'는 해안에."],
  "branch":["A bird sat on the branch.","새가 나뭇가지에 앉았어요.","'on the branch'."],
  "bush":["A cat hid behind the bush.","고양이가 덤불 뒤에 숨었어요.","과거시제(hide→hid)."],
  "valley":["The river flows through the valley.","강이 계곡을 통해 흘러요.","'through the valley'는 계곡을 통해."],
  "desert":["It is very hot in the desert.","사막은 매우 더워요.","비인칭 주어 it."],
  "jungle":["Many animals live in the jungle.","많은 동물이 정글에 살아요.","'in the jungle'."],
  "swamp":["Crocodiles live in the swamp.","악어는 늪에 살아요.","'in the swamp'."],
  "fin":["A fish swims with its fins.","물고기는 지느러미로 헤엄쳐요.","'with + 도구'."],
  "shell":["I found a shell on the beach.","나는 해변에서 조개껍데기를 찾았어요.","과거시제(find→found)."],
  "pearl":["The necklace has white pearls.","그 목걸이에는 흰 진주가 있어요.","복수 pearls."],
  "reef":["Colorful fish live near the reef.","알록달록한 물고기가 암초 근처에 살아요.","'near the reef'."],
  "tide":["The tide comes in at night.","밀물은 밤에 들어와요.","'come in'은 밀려들다."],
  "rainbow":["I see a rainbow after the rain.","비가 온 뒤 무지개가 보여요.","'after the rain'은 비가 온 뒤."],
  "comet":["A comet has a long tail.","혜성은 긴 꼬리가 있어요.","형용사 long."],
  "heat":["I can't stand the summer heat.","나는 여름 더위를 못 견뎌요.","'can't stand'은 못 견디다."],
  "mist":["Morning mist covers the hills.","아침 안개가 언덕을 덮어요.","3인칭 단수 covers."],
  "hail":["Hail fell from the sky.","우박이 하늘에서 떨어졌어요.","과거시제(fall→fell)."],
  "breeze":["A cool breeze feels nice.","시원한 산들바람이 기분 좋아요.","'feel + 형용사'."],
  "smoke":["Smoke rises from the chimney.","연기가 굴뚝에서 올라와요.","3인칭 단수 rises."],
  "flame":["The candle flame is small.","촛불의 불꽃이 작아요.","형용사 small."],
  "spark":["A spark started the fire.","불꽃이 불을 일으켰어요.","과거시제 started."],
  "ash":["Gray ash covered the ground.","회색 재가 땅을 덮었어요.","과거시제 covered."],
  "steam":["Steam rises from hot soup.","뜨거운 수프에서 김이 올라와요.","3인칭 단수 rises."],
  "bubble":["Children love soap bubbles.","아이들은 비눗방울을 좋아해요.","복수 bubbles."],
  "drop":["A drop of water fell.","물 한 방울이 떨어졌어요.","'a drop of ~'는 한 방울의."],
  "north":["Birds fly north in summer.","새는 여름에 북쪽으로 날아가요.","north는 부사(북쪽으로)."],
  "south":["It is warmer in the south.","남쪽이 더 따뜻해요.","비교급 warmer."],
  "east":["The sun rises in the east.","해는 동쪽에서 떠요.","'in the east'."],
  "west":["The sun sets in the west.","해는 서쪽으로 져요.","3인칭 단수 sets."],
  "left":["Turn left at the corner.","모퉁이에서 왼쪽으로 도세요.","명령문. left는 부사."],
  "right":["The store is on your right.","가게는 당신 오른쪽에 있어요.","'on your right'."],
  "world":["I want to travel the world.","나는 세계를 여행하고 싶어요.","'want to + 동사원형'."],
  "land":["The plane landed on the land.","비행기가 땅에 착륙했어요.","과거시제 landed."],
  "floor":["The keys are on the floor.","열쇠가 바닥에 있어요.","'on the floor'."],
  "stair":["Be careful on the stairs.","계단에서 조심해요.","stairs는 보통 복수로."],
  "step":["Watch your step.","발밑을 조심해요.","'watch your step'은 발밑 조심."],
  "stick":["The dog likes to fetch a stick.","개는 막대기 물어오는 걸 좋아해요.","'like to + 동사원형'."],
  "brick":["The house is made of brick.","그 집은 벽돌로 지어졌어요.","'be made of ~'."],
  "chain":["The dog is on a chain.","개가 사슬에 묶여 있어요.","'on a chain'."],
  "hook":["Hang your coat on the hook.","코트를 고리에 걸어요.","'on the hook'."],
  "lock":["Put a lock on the door.","문에 자물쇠를 채워요.","'on the door'."],
  "clay":["We made pots from clay.","우리는 점토로 그릇을 만들었어요.","'from clay'는 점토로."],
  "town":["I live in a small town.","나는 작은 마을에 살아요.","'in a small town'."],
  "city":["Seoul is a big city.","서울은 큰 도시예요.","'a big city'."],
  "edge":["Don't stand near the edge.","가장자리 근처에 서지 마세요.","부정 명령문."],
  "end":["We are near the end of the road.","우리는 길 끝 가까이 있어요.","'the end of ~'는 ~의 끝."],
  "room":["My room is small but cozy.","내 방은 작지만 아늑해요.","but은 대조 접속사."],
  "wall":["There is a picture on the wall.","벽에 그림이 있어요.","'on the wall'."],
  "roof":["A cat is on the roof.","고양이가 지붕 위에 있어요.","'on the roof'."],
  "gate":["Close the gate, please.","문을 닫아 주세요.","명령문."],
  "desk":["My books are on the desk.","내 책이 책상 위에 있어요.","'on the desk'."],
  "lamp":["Turn on the lamp.","램프를 켜요.","'turn on'은 켜다."],
  "fork":["Eat with a fork.","포크로 먹어요.","'with a fork'."],
  "dish":["Wash the dishes.","설거지를 해요.","'wash the dishes'는 설거지하다."],
  "bowl":["I ate a bowl of rice.","나는 밥 한 그릇을 먹었어요.","'a bowl of ~'는 한 그릇의."],
  "glass":["Pour water into the glass.","유리잔에 물을 따라요.","'into the glass'."],
  "jar":["The jam is in a jar.","잼이 병에 들어 있어요.","'in a jar'."],
  "pot":["Boil the water in a pot.","냄비에 물을 끓여요.","'in a pot'."],
  "pan":["Fry the egg in a pan.","팬에 달걀을 부쳐요.","'in a pan'."],
  "soap":["Wash your hands with soap.","비누로 손을 씻어요.","'with soap'."],
  "comb":["Comb your hair.","머리를 빗어요.","comb는 동사로도 쓰여요(빗다)."],
  "brush":["I brush my teeth twice a day.","나는 하루에 두 번 이를 닦아요.","'twice a day'는 하루에 두 번."],
  "broom":["Sweep the floor with a broom.","빗자루로 바닥을 쓸어요.","'with a broom'."],
  "rope":["Pull the rope hard.","밧줄을 세게 당겨요.","hard는 부사(세게)."],
  "tape":["Fix it with tape.","테이프로 그것을 고쳐요.","'with tape'."],
  "glue":["Stick the paper with glue.","풀로 종이를 붙여요.","'with glue'."],
  "bell":["The bell rings at noon.","종이 정오에 울려요.","3인칭 단수 rings."],
  "drum":["He plays the drums.","그는 드럼을 쳐요.","악기 앞에는 the."],
  "kite":["We flew a kite in the park.","우리는 공원에서 연을 날렸어요.","과거시제(fly→flew)."],
  "doll":["The girl loves her doll.","그 소녀는 인형을 좋아해요.","소유격 her."],
  "toy":["The baby plays with toys.","아기가 장난감을 가지고 놀아요.","'play with ~'는 ~을 가지고 놀다."],
  "ring":["She wears a gold ring.","그녀는 금반지를 껴요.","현재시제 wears."],
  "coin":["I have some coins in my pocket.","주머니에 동전이 좀 있어요.","'in my pocket'."],
  "frame":["Put the photo in a frame.","사진을 액자에 넣어요.","'in a frame'."],
  "shelf":["The books are on the shelf.","책이 선반에 있어요.","shelf의 복수는 shelves."],
  "drawer":["Open the top drawer.","맨 위 서랍을 열어요.","top은 맨 위의."],
  "closet":["Hang the clothes in the closet.","옷을 옷장에 걸어요.","'in the closet'."],
  "pillow":["This pillow is soft.","이 베개는 부드러워요.","'be + 형용사'."],
  "blanket":["Cover yourself with a blanket.","담요로 몸을 덮어요.","'with a blanket'."],
  "sheet":["Change the bed sheets.","침대 시트를 갈아요.","복수 sheets."],
  "curtain":["Open the curtains.","커튼을 열어요.","복수 curtains."],
  "carpet":["The carpet is soft and warm.","카펫이 부드럽고 따뜻해요.","and로 형용사 연결."],
  "fan":["Turn on the fan.","선풍기를 켜요.","'turn on'."],
  "oven":["Bake the cake in the oven.","오븐에 케이크를 구워요.","'in the oven'."],
  "sink":["Wash the dishes in the sink.","싱크대에서 설거지를 해요.","'in the sink'."],
  "tub":["The baby is in the tub.","아기가 욕조에 있어요.","'in the tub'."],
  "stove":["Cook on the stove.","난로에서 요리해요.","'on the stove'."],
  "hut":["They live in a small hut.","그들은 작은 오두막에 살아요.","'in a small hut'."],
  "tent":["We slept in a tent.","우리는 텐트에서 잤어요.","과거시제(sleep→slept)."],
  "cart":["Push the shopping cart.","쇼핑 카트를 밀어요.","명령문."],
  "sled":["Kids ride sleds in winter.","아이들은 겨울에 썰매를 타요.","'in winter'."],
  "horn":["The car horn is loud.","자동차 경적이 시끄러워요.","형용사 loud."],
  "flute":["She plays the flute well.","그녀는 플루트를 잘 불어요.","well은 부사."],
  "cube":["Add an ice cube.","얼음 한 조각을 넣어요.","'ice cube'는 얼음 조각."],
  "cap":["He wears a baseball cap.","그는 야구 모자를 써요.","현재시제 wears."],
  "coat":["Put on your coat.","코트를 입어요.","'put on'은 입다."],
  "shirt":["This shirt is too big.","이 셔츠는 너무 커요.","'too + 형용사'."],
  "skirt":["She is wearing a blue skirt.","그녀는 파란 치마를 입고 있어요.","현재진행형."],
  "dress":["What a pretty dress!","정말 예쁜 드레스다!","감탄문 'What a + 형용사 + 명사!'."],
  "sock":["I can't find my socks.","양말을 못 찾겠어요.","복수 socks."],
  "shoe":["Tie your shoes.","신발 끈을 묶어요.","복수 shoes."],
  "boot":["Wear your boots in the snow.","눈에서는 부츠를 신어요.","복수 boots."],
  "glove":["Put on your gloves.","장갑을 껴요.","복수 gloves."],
  "scarf":["She wears a warm scarf.","그녀는 따뜻한 목도리를 둘러요.","형용사 warm."],
  "belt":["Fasten your belt.","벨트를 매요.","'fasten'은 매다."],
  "jeans":["I wear blue jeans every day.","나는 매일 청바지를 입어요.","jeans는 항상 복수."],
  "pants":["These pants are too long.","이 바지는 너무 길어요.","pants는 항상 복수라 these/are."],
  "vest":["He wears a vest over his shirt.","그는 셔츠 위에 조끼를 입어요.","'over ~'는 ~위에."],
  "robe":["She put on a bath robe.","그녀는 목욕 가운을 입었어요.","과거시제(put은 동일형)."],
  "tie":["He wears a tie to work.","그는 회사에 넥타이를 매고 가요.","'to work'는 회사에."],
  "cloth":["Clean it with a wet cloth.","젖은 천으로 그것을 닦아요.","형용사 wet."],
  "bike":["I ride my bike to school.","나는 자전거를 타고 학교에 가요.","'ride a bike'는 자전거를 타다."],
  "train":["I take the train every morning.","나는 매일 아침 기차를 타요.","'take the train'."],
  "truck":["The truck carries boxes.","트럭이 상자를 날라요.","3인칭 단수 carries."],
  "boat":["We rowed the boat across the lake.","우리는 호수를 가로질러 배를 저었어요.","과거시제 rowed."],
  "jet":["A jet flies very fast.","제트기는 매우 빨리 날아요.","fast는 부사."],
  "taxi":["Let's take a taxi.","택시를 타자.","'take a taxi'."],
  "van":["The van is full of boxes.","밴이 상자로 가득해요.","'full of ~'는 ~로 가득한."],
  "cab":["I called a cab.","나는 택시를 불렀어요.","과거시제 called."],
  "plane":["The plane takes off at six.","비행기가 6시에 이륙해요.","'take off'는 이륙하다."],
  "wheel":["A car has four wheels.","자동차는 바퀴가 네 개예요.","수 four."],
  "sail":["The boat has a white sail.","그 배는 흰 돛이 있어요.","형용사 white."],
  "subway":["I go to work by subway.","나는 지하철로 출근해요.","'by subway'는 지하철로."],
  "one":["I have only one brother.","나는 형이 한 명뿐이에요.","only는 ~만."],
  "two":["I have two cats.","나는 고양이 두 마리가 있어요.","복수 cats."],
  "three":["The movie starts in three minutes.","영화가 3분 후에 시작해요.","'in three minutes'는 3분 후에."],
  "four":["A table has four legs.","탁자는 다리가 네 개예요.","수 four."],
  "five":["I wake up at five.","나는 5시에 일어나요.","'at five'."],
  "six":["School ends at six.","학교는 6시에 끝나요.","3인칭 단수 ends."],
  "seven":["There are seven days in a week.","일주일은 칠 일이에요.","'There are + 복수'."],
  "eight":["A spider has eight legs.","거미는 다리가 여덟 개예요.","수 eight."],
  "nine":["The store opens at nine.","가게는 9시에 열어요.","3인칭 단수 opens."],
  "ten":["I have ten fingers.","나는 손가락이 열 개예요.","수 ten."],
  "zero":["The temperature is below zero.","기온이 영하예요.","'below zero'는 영하."],
  "gray":["The sky is gray today.","오늘 하늘이 회색이에요.","'be + 형용사'."],
  "brown":["She has brown eyes.","그녀는 갈색 눈을 가졌어요.","형용사 brown."],
  "silver":["I bought a silver ring.","나는 은반지를 샀어요.","과거시제 bought."],
  "tan":["His skin is tan.","그의 피부는 황갈색이에요.","'be + 형용사'."],
  "navy":["She wears a navy jacket.","그녀는 남색 재킷을 입어요.","형용사 navy."],
  "baby":["The baby is sleeping.","아기가 자고 있어요.","현재진행형."],
  "boy":["The boy is playing soccer.","소년이 축구를 하고 있어요.","현재진행형."],
  "girl":["The girl sings beautifully.","소녀가 아름답게 노래해요.","beautifully는 부사."],
  "man":["The man is reading a newspaper.","남자가 신문을 읽고 있어요.","현재진행형."],
  "woman":["The woman is a doctor.","그 여자는 의사예요.","'be + 직업'."],
  "kid":["The kids are playing outside.","아이들이 밖에서 놀고 있어요.","복수 kids."],
  "son":["Their son is ten years old.","그들의 아들은 열 살이에요.","'~ years old'는 ~살."],
  "aunt":["My aunt lives in Busan.","우리 이모는 부산에 살아요.","3인칭 단수 lives."],
  "uncle":["My uncle is very kind.","우리 삼촌은 매우 친절해요.","'be + 형용사'."],
  "mom":["My mom makes great food.","우리 엄마는 음식을 잘 만들어요.","3인칭 단수 makes."],
  "dad":["My dad drives a truck.","우리 아빠는 트럭을 몰아요.","3인칭 단수 drives."],
  "child":["The child is very smart.","그 아이는 아주 똑똑해요.","child의 복수는 children."],
  "adult":["This movie is for adults.","이 영화는 어른용이에요.","'for adults'는 어른용."],
  "lady":["The lady is wearing a hat.","그 숙녀는 모자를 쓰고 있어요.","현재진행형."],
  "hero":["He is my hero.","그는 내 영웅이에요.","소유격 my."],
  "queen":["The queen lives in a palace.","여왕은 궁전에 살아요.","'in a palace'."],
  "prince":["The prince married a princess.","왕자는 공주와 결혼했어요.","과거시제 married."],
  "twin":["She has a twin sister.","그녀는 쌍둥이 자매가 있어요.","형용사처럼 쓰인 twin."],
  "nurse":["The nurse helps the doctor.","간호사가 의사를 도와요.","3인칭 단수 helps."],
  "pet":["Do you have a pet?","애완동물 키우세요?","의문문 'Do you ~?'."],
  "word":["What does this word mean?","이 단어는 무슨 뜻이에요?","'What does ~ mean?'은 무슨 뜻이냐."],
  "line":["Draw a straight line.","직선을 그어요.","형용사 straight."],
  "page":["Open your book to page ten.","책 10쪽을 펴요.","'to page ten'은 10쪽을."],
  "note":["I left you a note.","너에게 메모를 남겼어.","과거시제(leave→left)."],
  "song":["This is my favorite song.","이건 내가 가장 좋아하는 노래예요.","favorite은 가장 좋아하는."],
  "game":["Let's play a game.","게임 하자.","'play a game'."],
  "team":["Our team won the match.","우리 팀이 경기에서 이겼어요.","과거시제(win→won)."],
  "wish":["Make a wish!","소원을 빌어요!","'make a wish'는 소원을 빌다."],
  "joke":["He told a funny joke.","그는 재미있는 농담을 했어요.","과거시제(tell→told)."],
  "story":["Tell me a story.","이야기를 들려줘.","'tell + 사람 + 사물'(4형식)."],
  "dream":["My dream is to be a pilot.","내 꿈은 조종사가 되는 거예요.","'to be ~'는 ~이 되는 것."],
  "smile":["She has a lovely smile.","그녀는 사랑스러운 미소를 지녔어요.","형용사 lovely."],
  "tear":["Tears ran down her face.","눈물이 그녀의 얼굴에 흘러내렸어요.","과거시제(run→ran)."],
  "kiss":["She gave him a kiss.","그녀는 그에게 키스를 했어요.","'give + 사람 + 사물'(4형식)."],
  "hug":["Give me a hug.","나를 안아 줘.","'give a hug'는 안아주다."],
  "gift":["This is a gift for you.","이건 너를 위한 선물이야.","'for you'는 너를 위한."],
  "news":["The news is very sad.","그 소식은 매우 슬퍼요.","news는 단수 취급(is)."],
  "fact":["That is a well-known fact.","그것은 잘 알려진 사실이에요.","well-known은 잘 알려진."],
  "idea":["That is a great idea.","그거 정말 좋은 생각이에요.","형용사 great."],
  "plan":["Do you have a plan?","계획이 있어요?","의문문."],
  "rule":["Follow the rules.","규칙을 따라요.","복수 rules."],
  "fun":["We had a lot of fun.","우리는 정말 즐거웠어요.","'a lot of fun'은 큰 재미."],
  "job":["She has a good job.","그녀는 좋은 직업을 가졌어요.","형용사 good."],
  "shop":["The shop opens at nine.","가게는 9시에 열어요.","3인칭 단수 opens."],
  "store":["I bought it at the store.","나는 가게에서 그것을 샀어요.","'at the store'."],
  "park":["Let's walk in the park.","공원에서 산책하자.","'in the park'."],
  "zoo":["We saw lions at the zoo.","우리는 동물원에서 사자를 봤어요.","과거시제(see→saw)."],
  "farm":["They grow corn on the farm.","그들은 농장에서 옥수수를 길러요.","'on the farm'."],
  "bank":["I went to the bank.","나는 은행에 갔어요.","과거시제(go→went)."],
  "mall":["Let's meet at the mall.","쇼핑몰에서 만나자.","'at the mall'."],
  "path":["Follow this path to the lake.","호수까지 이 길을 따라가요.","'to the lake'는 호수까지."],
  "yard":["The kids play in the yard.","아이들이 마당에서 놀아요.","'in the yard'."],
  "flag":["The flag is red and blue.","그 깃발은 빨간색과 파란색이에요.","and로 색 연결."]
};
