/* ============================================================
   오답노트용 예문 데이터 — { 영단어: ["영어 예문", "한글 번역", "문법 설명"] }
   대표(빈출) 단어 위주. 여기 없는 단어는 game이 학습용 폴백 예문을 자동 생성.
   점진적으로 단어별 예문을 추가하면 그대로 오답노트에 반영됨.
   ============================================================ */
window.EXAMPLES = {
  "cat":["The cat is sleeping on the bed.","고양이가 침대에서 자고 있다.","현재진행형 'is + -ing'은 지금 하고 있는 동작을 나타냅니다."],
  "dog":["My dog likes to play in the park.","내 개는 공원에서 노는 걸 좋아한다.","주어가 3인칭 단수(My dog)라 동사에 -s가 붙어 'likes'. 'like to + 동사원형'은 ~하기를 좋아하다."],
  "sun":["The sun rises in the east.","해는 동쪽에서 뜬다.","변하지 않는 사실은 현재시제로 씁니다. 3인칭 단수라 'rises'."],
  "moon":["The moon is bright tonight.","오늘 밤 달이 밝다.","'be동사 + 형용사' 형태로 상태를 설명합니다(is bright)."],
  "star":["I can see many stars in the sky.","하늘에 많은 별이 보인다.","조동사 'can(~할 수 있다)' 뒤에는 항상 동사원형(see)이 옵니다."],
  "book":["She is reading an interesting book.","그녀는 재미있는 책을 읽고 있다.","현재진행형 'is + -ing'. 형용사 interesting이 명사 book을 꾸밉니다."],
  "fish":["We caught a big fish today.","우리는 오늘 큰 물고기를 잡았다.","과거시제. catch는 불규칙 동사로 과거형이 'caught'입니다."],
  "bird":["A bird is singing on the tree.","새가 나무 위에서 노래하고 있다.","현재진행형 'is + -ing'. 장소는 전치사 on으로 나타냅니다."],
  "tree":["There is a tall tree in the garden.","정원에 키 큰 나무가 있다.","'There is + 단수명사'는 '~가 있다'라는 존재를 나타냅니다."],
  "rain":["The rain stopped in the afternoon.","오후에 비가 그쳤다.","과거시제. 규칙 동사는 끝에 -ed를 붙입니다(stop→stopped, p 중복)."],
  "egg":["I eat two eggs every morning.","나는 매일 아침 계란 두 개를 먹는다.","반복되는 습관은 현재시제. 복수(two eggs)라 -s가 붙습니다."],
  "hand":["Please raise your hand.","손을 들어 주세요.","명령문은 동사원형으로 시작합니다. Please를 붙이면 공손해집니다."],
  "door":["Close the door, please.","문 좀 닫아 주세요.","동사원형으로 시작하는 명령문입니다."],
  "ball":["The children are playing with a ball.","아이들이 공을 가지고 놀고 있다.","주어가 복수(children)라 현재진행형이 'are + -ing'."],
  "king":["The king lived in a big castle.","왕은 큰 성에 살았다.","과거시제(live→lived). 'in + 장소'로 어디에 사는지 나타냅니다."],
  "milk":["I drink a glass of milk every day.","나는 매일 우유 한 잔을 마신다.","'a glass of ~'는 셀 수 없는 명사의 양을 세는 표현입니다."],
  "water":["Can I have a glass of water?","물 한 잔 주시겠어요?","'Can I ~?'는 허락·요청을 부드럽게 묻는 표현입니다."],
  "house":["They live in a small house.","그들은 작은 집에 산다.","현재시제. 주어가 복수(They)라 동사는 원형 그대로 live."],
  "car":["He drives his car to work.","그는 차를 몰고 출근한다.","3인칭 단수 주어(He)라 동사에 -s가 붙어 'drives'."],
  "bus":["I take the bus to school.","나는 버스를 타고 학교에 간다.","'take the bus'는 버스를 타다라는 관용 표현입니다."],
  "apple":["An apple a day keeps the doctor away.","하루 사과 한 개면 의사가 필요 없다.","유명한 속담. 모음 앞이라 'An', 3인칭 단수라 'keeps'."],
  "run":["I run every morning.","나는 매일 아침 달린다.","반복되는 습관은 현재시제로 표현합니다."],
  "eat":["Let's eat lunch together.","같이 점심 먹자.","'Let's + 동사원형'은 '~하자'라는 제안 표현입니다."],
  "go":["I go to school by bus.","나는 버스로 학교에 간다.","'by + 교통수단'은 ~을 타고라는 뜻(무관사)."],
  "come":["Please come to my party.","내 파티에 와 줘.","동사원형으로 시작하는 명령문. 방향은 전치사 to."],
  "see":["I can see the mountain from here.","여기서 산이 보인다.","조동사 can 뒤에는 동사원형(see). 'from ~'은 출발점."],
  "make":["She wants to make a cake.","그녀는 케이크를 만들고 싶어 한다.","'want to + 동사원형'은 ~하고 싶다. 3인칭 단수라 wants."],
  "take":["Take an umbrella with you.","우산을 가져가.","명령문. 'with you'는 '몸에 지니고'라는 뉘앙스를 더합니다."],
  "give":["Give me your hand.","손을 줘.","'give + 사람 + 사물'은 ~에게 …을 주다(4형식)."],
  "know":["I know the answer.","나는 답을 안다.","현재시제로 알고 있는 상태를 나타냅니다."],
  "want":["I want a cup of coffee.","나는 커피 한 잔을 원한다.","'a cup of ~'는 컵에 담긴 음료의 양을 세는 표현."],
  "need":["You need to rest.","너는 쉬어야 한다.","'need to + 동사원형'은 ~할 필요가 있다."],
  "help":["Can you help me?","나를 도와줄 수 있니?","'Can you ~?'는 상대에게 부탁·요청하는 표현입니다."],
  "walk":["We walk to the park every day.","우리는 매일 공원까지 걷는다.","현재시제 습관. 'to + 장소'는 목적지를 나타냅니다."],
  "jump":["The cat can jump very high.","그 고양이는 아주 높이 뛸 수 있다.","조동사 can + 동사원형. high는 동사를 꾸미는 부사."],
  "read":["I like to read books at night.","나는 밤에 책 읽는 걸 좋아한다.","'like to + 동사원형'. 'at night'은 밤에라는 시간 표현."],
  "write":["Please write your name here.","여기에 이름을 써 주세요.","명령문. here는 장소를 나타내는 부사입니다."],
  "sleep":["Babies sleep a lot.","아기들은 잠을 많이 잔다.","일반적 사실은 현재시제. 'a lot'은 '많이'라는 부사구."],
  "open":["Open the window, please.","창문 좀 열어 주세요.","동사원형으로 시작하는 명령문입니다."],
  "buy":["I want to buy a new phone.","나는 새 전화기를 사고 싶다.","'want to + 동사원형'. 형용사 new가 명사 phone을 꾸밉니다."],
  "meet":["Let's meet at six.","6시에 만나자.","'Let's + 동사원형'(제안). 'at + 시각'은 정확한 시간."],
  "play":["The kids play in the yard.","아이들이 마당에서 논다.","현재시제. 'in + 장소'로 어디서 노는지 나타냅니다."],
  "drink":["Drink more water.","물을 더 마셔.","명령문. more는 '더 많은'이라는 비교 표현입니다."],
  "sing":["She loves to sing.","그녀는 노래하는 걸 좋아한다.","'love to + 동사원형'. 3인칭 단수라 loves."],
  "dance":["They dance very well.","그들은 춤을 아주 잘 춘다.","well은 동사 dance를 꾸미는 부사(잘)입니다."],
  "learn":["I want to learn English.","나는 영어를 배우고 싶다.","'want to + 동사원형'은 ~하고 싶다."],
  "teach":["She teaches math at school.","그녀는 학교에서 수학을 가르친다.","3인칭 단수 주어라 -es가 붙어 'teaches'."],
  "study":["I study every evening.","나는 매일 저녁 공부한다.","반복되는 습관은 현재시제로 표현합니다."],
  "speak":["Can you speak English?","영어를 할 수 있나요?","'Can you ~?'로 능력·가능을 묻습니다."],
  "hear":["I can hear music.","음악이 들린다.","조동사 can + 동사원형(hear)."],
  "think":["I think you are right.","네 말이 맞는 것 같아.","'I think (that) + 문장'은 ~라고 생각하다. that은 생략 가능."],
  "like":["I like ice cream.","나는 아이스크림을 좋아한다.","현재시제로 좋아하는 상태를 나타냅니다."],
  "love":["I love my family.","나는 내 가족을 사랑한다.","현재시제. my는 소유격(나의)."],
  "hate":["I hate spiders.","나는 거미가 싫다.","일반적인 대상은 복수형(spiders)으로 씁니다."],
  "enjoy":["We enjoy playing soccer.","우리는 축구하는 걸 즐긴다.","enjoy 뒤에는 동명사(-ing)가 옵니다. 'to부정사'를 쓰지 않아요."],
  "start":["The movie starts at seven.","영화는 7시에 시작한다.","3인칭 단수라 starts. 'at + 시각'."],
  "finish":["I need to finish my homework.","나는 숙제를 끝내야 한다.","'need to + 동사원형'은 ~해야 한다."],
  "happy":["She looks very happy today.","그녀는 오늘 매우 행복해 보인다.","'look + 형용사'는 ~해 보이다. very는 형용사를 강조."],
  "big":["They live in a big city.","그들은 큰 도시에 산다.","형용사(big)가 명사(city) 앞에서 꾸며 줍니다."],
  "small":["I have a small dog.","나는 작은 개가 있다.","'have'는 가지고 있다. 형용사 small이 dog을 꾸밉니다."],
  "good":["This is a good idea.","이건 좋은 생각이야.","'be동사 + 형용사 + 명사' 구조입니다."],
  "bad":["The weather is bad today.","오늘 날씨가 나쁘다.","'be동사 + 형용사'로 상태를 설명합니다."],
  "hot":["The soup is very hot.","수프가 매우 뜨겁다.","very(매우)가 형용사 hot을 강조합니다."],
  "cold":["It is cold outside.","밖이 춥다.","날씨·상황을 말할 때 주어로 It을 씁니다(비인칭 it)."],
  "new":["I bought a new bike.","나는 새 자전거를 샀다.","과거시제. buy의 과거형은 불규칙형 'bought'."],
  "old":["This is an old book.","이건 오래된 책이다.","모음(o)으로 시작하는 단어 앞이라 'a'가 아니라 'an'."],
  "fast":["He is a fast runner.","그는 빠른 주자이다.","fast는 형용사로 명사 runner를 꾸밉니다."],
  "slow":["The turtle is very slow.","거북이는 매우 느리다.","'be + 형용사'. very로 정도를 강조합니다."],
  "long":["She has long hair.","그녀는 긴 머리를 가졌다.","3인칭 단수라 has. 형용사 long이 hair를 꾸밉니다."],
  "short":["He is short but strong.","그는 키가 작지만 힘이 세다.","but은 반대 내용을 잇는 접속사(그러나)."],
  "tall":["My brother is very tall.","내 형은 키가 매우 크다.","'be + 형용사'. very가 tall을 강조합니다."],
  "clean":["Please keep the room clean.","방을 깨끗하게 유지해 주세요.","'keep + 목적어 + 형용사'는 ~을 …한 상태로 유지하다(5형식)."],
  "tired":["I am very tired today.","나는 오늘 매우 피곤하다.","'be동사 + 형용사'. tired는 감정·상태 형용사."],
  "hungry":["I am hungry. Let's eat.","배고파. 먹자.","'be + 형용사'로 상태를, 'Let's + 동사원형'으로 제안을 합니다."],
  "angry":["Don't be angry with me.","나한테 화내지 마.","'Don't + 동사원형'은 부정 명령문(~하지 마)."],
  "friend":["She is my best friend.","그녀는 내 가장 친한 친구이다.","best는 good의 최상급(가장 좋은)."],
  "family":["I love spending time with my family.","나는 가족과 시간 보내는 걸 좋아한다.","'spend + 시간 + -ing'은 ~하며 시간을 보내다."],
  "school":["I go to school every day.","나는 매일 학교에 간다.","'go to school'은 등교하다라는 관용 표현(무관사)."],
  "mother":["My mother cooks delicious food.","우리 엄마는 맛있는 음식을 요리한다.","3인칭 단수 주어라 동사에 -s(cooks)."],
  "father":["My father works in an office.","우리 아빠는 사무실에서 일한다.","3인칭 단수라 works. 'in + 장소'."],
  "food":["Korean food is delicious.","한국 음식은 맛있다.","'be동사 + 형용사'로 맛·상태를 설명합니다."],
  "money":["I save money every month.","나는 매달 돈을 모은다.","현재시제 습관. money는 셀 수 없는 명사라 -s를 안 붙입니다."],
  "time":["What time is it now?","지금 몇 시야?","'What time is it?'은 시간을 묻는 정해진 표현입니다."],
  "work":["I work from nine to six.","나는 9시부터 6시까지 일한다.","'from A to B'는 A부터 B까지."],
  "home":["I want to go home.","나는 집에 가고 싶다.","'go home'은 집에 가다(home은 부사라 to가 없음)."],
  "night":["Good night! Sleep well.","잘 자! 푹 자.","명령문. well은 동사 sleep을 꾸미는 부사(잘)."],
  "day":["Have a nice day!","좋은 하루 보내!","동사원형으로 시작하는 명령문 형태의 인사말."],
  "name":["What is your name?","네 이름이 뭐야?","의문사 What으로 시작하는 의문문입니다."],
  "color":["What is your favorite color?","네가 가장 좋아하는 색이 뭐야?","의문사 의문문. favorite은 '가장 좋아하는'."],
  "foot":["My right foot hurts.","오른발이 아파요.","foot의 복수형은 feet(불규칙)이에요."],
  "bear":["A bear is sleeping in the cave.","곰이 동굴에서 자고 있어요.","현재진행형 'is + -ing'."],
  "cup":["Can I have a cup of tea?","차 한 잔 주시겠어요?","'a cup of ~'는 잔에 담긴 양을 세는 표현."],
  "pen":["Write it down with this pen.","이 펜으로 적어요.","'with + 도구'는 ~로(수단)."],
  "box":["Put the toys in the box.","장난감을 상자에 넣어요.","'in + 장소'는 ~안에."],
  "bed":["I go to bed at ten.","나는 10시에 잠자리에 들어요.","'go to bed'는 잠자리에들다(무관사)."],
  "hat":["He is wearing a red hat.","그는 빨간 모자를 쓰고 있어요.","wear는 입다·쓰다·착용하다."],
  "map":["Look at the map.","지도를 봐요.","명령문은 동사원형으로 시작해요."],
  "key":["I lost my car key.","차 열쇠를 잃어버렸어요.","과거시제(lose→lost, 불규칙)."],
  "bag":["This bag is too heavy.","이 가방은 너무 무거워요.","'too + 형용사'는 너무 ~한."],
  "cow":["The cow gives us milk.","소는 우리에게 우유를 줘요.","'give + 사람 + 사물'(4형식)."],
  "pig":["Pigs are pink and cute.","돼지는 분홍색이고 귀여워요.","복수 주어라 be동사는 are."],
  "ant":["An ant is very small.","개미는 아주 작아요.","모음 앞이라 부정관사 'an'."],
  "bee":["A bee is on the flower.","벌이 꽃 위에 있어요.","'on + 장소'는 ~위에."],
  "fox":["The fox runs very fast.","여우는 매우 빨리 달려요.","3인칭 단수라 runs."],
  "owl":["An owl sleeps in the day.","부엉이는 낮에 자요.","'in the day'는 낮에."],
  "leg":["My legs are tired.","다리가 피곤해요.","복수 legs라 be동사 are."],
  "eye":["Close your eyes.","눈을 감아요.","명령문. eyes는 eye의 복수."],
  "ear":["Rabbits have long ears.","토끼는 긴 귀를 가졌어요.","have는 가지고있다."],
  "lip":["Her lips are red.","그녀의 입술은 빨개요.","소유격 her(그녀의)."],
  "arm":["He has strong arms.","그는 튼튼한 팔을 가졌어요.","형용사 strong이 arms를 꾸며요."],
  "sky":["The sky is blue today.","오늘 하늘이 파래요.","'be + 형용사'로 상태를."],
  "sea":["We swim in the sea.","우리는 바다에서 수영해요.","'in the sea'는 바다에서."],
  "ice":["The ice is cold.","얼음은 차가워요.","ice는 셀 수 없는 명사."],
  "fire":["Be careful with fire.","불을 조심해요.","'be careful with ~'는 ~을 조심하다."],
  "wind":["The wind is strong.","바람이 세요.","'be + 형용사'."],
  "snow":["Children play in the snow.","아이들이 눈에서 놀아요.","snow는 셀 수 없는 명사."],
  "road":["Cross the road carefully.","길을 조심히 건너요.","carefully는 부사(조심히)."],
  "ship":["The ship sails on the sea.","배가 바다를 항해해요.","3인칭 단수 sails."],
  "wing":["Birds fly with their wings.","새는 날개로 날아요.","'with + 도구'."],
  "nose":["The dog has a wet nose.","개는 코가 촉촉해요.","형용사 wet이 nose를 꾸며요."],
  "rice":["I eat rice every day.","나는 매일 밥을 먹어요.","현재시제(습관)."],
  "hen":["The hen lays eggs.","암탉이 알을 낳아요.","3인칭 단수 lays."],
  "duck":["A duck swims in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'는 연못에서."],
  "goat":["The goat eats grass.","염소가 풀을 먹어요.","3인칭 단수 eats."],
  "lion":["The lion is the king of animals.","사자는 동물의 왕이에요.","'the king of ~'는 ~의 왕."],
  "tiger":["A tiger has stripes.","호랑이는 줄무늬가 있어요.","have/has는 가지고있다."],
  "zebra":["A zebra looks like a horse.","얼룩말은 말처럼 생겼어요.","'look like + 명사'는 ~처럼 보이다."],
  "wolf":["Wolves live in the forest.","늑대는 숲에 살아요.","wolf의 복수는 wolves(불규칙)."],
  "deer":["A deer ran into the woods.","사슴이 숲으로 뛰어 들어갔어요.","과거시제(run→ran)."],
  "frog":["The frog jumps high.","개구리가 높이 뛰어요.","high는 부사(높이)."],
  "sheep":["The sheep are in the field.","양들이 들판에 있어요.","sheep은 단수·복수 같은꼴."],
  "horse":["She rides a horse well.","그녀는 말을 잘 타요.","well은 부사(잘)."],
  "mouse":["A mouse is afraid of cats.","쥐는 고양이를 무서워해요.","'be afraid of ~'는 ~을 무서워하다."],
  "rabbit":["The rabbit has big ears.","토끼는 큰 귀를 가졌어요.","형용사 big이 ears를 꾸며요."],
  "snake":["A snake has no legs.","뱀은 다리가 없어요.","'have no ~'는 ~이 없다."],
  "crab":["The crab walks sideways.","게는 옆으로 걸어요.","sideways는 부사(옆으로)."],
  "shark":["A shark has sharp teeth.","상어는 날카로운 이빨이 있어요.","tooth의 복수는 teeth."],
  "whale":["The whale is the biggest animal.","고래는 가장 큰 동물이에요.","최상급 biggest."],
  "seal":["A seal can swim fast.","물개는 빨리 헤엄칠 수 있어요.","조동사 can + 동사원형."],
  "swan":["The swan is white and graceful.","백조는 하얗고 우아해요.","and로 형용사 두 개 연결."],
  "eagle":["An eagle flies high in the sky.","독수리가 하늘 높이 날아요.","high는 부사."],
  "dove":["A dove is a symbol of peace.","비둘기는 평화의 상징이에요.","'a symbol of ~'는 ~의 상징."],
  "crow":["The crow is black.","까마귀는 검어요.","'be + 형용사'."],
  "goose":["A goose has a long neck.","거위는 목이 길어요.","goose의 복수는 geese."],
  "panda":["The panda eats bamboo.","판다는 대나무를 먹어요.","3인칭 단수 eats."],
  "monkey":["Monkeys love bananas.","원숭이는 바나나를 좋아해요.","복수 주어라 love(원형)."],
  "camel":["A camel lives in the desert.","낙타는 사막에 살아요.","'in the desert'는 사막에서."],
  "kitten":["The kitten is so cute.","새끼고양이가 너무 귀여워요.","'so + 형용사'는 너무 ~한."],
  "puppy":["My puppy follows me everywhere.","내 강아지는 어디든 나를 따라와요.","everywhere는 부사(어디든)."],
  "chick":["The chick is yellow and small.","병아리는 노랗고 작아요.","and로 형용사 연결."],
  "lamb":["A lamb is a baby sheep.","새끼양은 아기 양이에요.","'A is B' 정의 문장."],
  "bull":["The bull is very strong.","황소는 매우 힘이 세요.","'very + 형용사'."],
  "bug":["There is a bug on the wall.","벽에 벌레가 있어요.","'There is + 단수'는 ~가 있다."],
  "worm":["The bird ate a worm.","새가 벌레를 먹었어요.","과거시제(eat→ate)."],
  "spider":["A spider has eight legs.","거미는 다리가 여덟 개예요.","수를 나타내는 eight."],
  "snail":["The snail moves very slowly.","달팽이는 아주 느리게 움직여요.","slowly는 부사(느리게)."],
  "turtle":["A turtle lives a long time.","거북이는 오래 살아요.","'a long time'은 오랫동안."],
  "shrimp":["I like fried shrimp.","나는 새우튀김을 좋아해요.","fried는 형용사(튀긴)."],
  "hippo":["The hippo stays in the water.","하마는 물 속에 머물러요.","'in the water'는 물 속에."],
  "rhino":["A rhino has a big horn.","코뿔소는 큰 뿔이 있어요.","형용사 big이 horn을 꾸며요."],
  "bat":["Bats fly at night.","박쥐는 밤에 날아요.","'at night'은 밤에."],
  "mole":["A mole digs under the ground.","두더지는 땅 밑을 파요.","'under the ground'는 땅 밑을."],
  "otter":["The otter swims in the river.","수달이 강에서 헤엄쳐요.","'in the river'는 강에서."],
  "beaver":["A beaver builds a dam.","비버는 댐을 지어요.","3인칭 단수 builds."],
  "squirrel":["The squirrel eats nuts.","다람쥐가 견과를 먹어요.","3인칭 단수 eats."],
  "ox":["An ox pulls the cart.","소가 수레를 끌어요.","ox의 복수는 oxen."],
  "head":["I have a headache in my head.","머리가 아파요.","headache는 두통."],
  "hair":["She has long black hair.","그녀는 길고 검은 머리를 가졌어요.","hair는 보통 셀 수 없는 명사."],
  "face":["Wash your face.","얼굴을 씻어요.","명령문."],
  "mouth":["Open your mouth.","입을 벌려요.","명령문."],
  "tooth":["Brush your teeth.","이를 닦아요.","tooth의 복수는 teeth."],
  "neck":["A giraffe has a long neck.","기린은 목이 길어요.","형용사 long이 neck을 꾸며요."],
  "back":["My back hurts.","등이 아파요.","back은 등·뒤."],
  "knee":["I hurt my knee.","무릎을 다쳤어요.","과거시제(hurt는 불규칙·동일형)."],
  "toe":["I have ten toes.","나는 발가락이 열 개예요.","수 ten."],
  "thumb":["He hurt his thumb.","그는 엄지를 다쳤어요.","소유격 his."],
  "chin":["She has a small chin.","그녀는 턱이 작아요.","형용사 small."],
  "cheek":["The baby has soft cheeks.","아기는 볼이 부드러워요.","형용사 soft."],
  "skin":["Babies have soft skin.","아기는 피부가 부드러워요.","skin은 셀 수 없는 명사."],
  "bone":["The dog likes bones.","개는 뼈를 좋아해요.","복수 bones."],
  "heart":["My heart beats fast.","심장이 빠르게 뛰어요.","fast는 부사."],
  "blood":["Blood is red.","피는 빨개요.","blood는 셀 수 없는 명사."],
  "chest":["He has a strong chest.","그는 가슴이 튼튼해요.","형용사 strong."],
  "heel":["My heel hurts.","발뒤꿈치가 아파요.","heel은 발뒤꿈치."],
  "palm":["She held it in her palm.","그녀는 손바닥에 그것을 쥐었어요.","과거시제(hold→held)."],
  "nail":["Cut your nails.","손톱을 깎아요.","명령문. nails 복수."],
  "wrist":["I wear a watch on my wrist.","나는 손목에 시계를 차요.","'on my wrist'는 손목에."],
  "brain":["The brain is very important.","뇌는 매우 중요해요.","'be + 형용사'."],
  "tongue":["Stick out your tongue.","혀를 내밀어요.","'stick out'은 내밀다."],
  "throat":["I have a sore throat.","목이 아파요.","sore는 형용사(아픈)."],
  "bread":["I eat bread for breakfast.","나는 아침으로 빵을 먹어요.","'for breakfast'는 아침으로."],
  "meat":["I don't eat meat.","나는 고기를 안 먹어요.","부정문 'don't + 동사원형'."],
  "soup":["The soup is hot.","수프가 뜨거워요.","'be + 형용사'."],
  "cake":["Let's make a cake.","케이크를 만들자.","'Let's + 동사원형'(제안)."],
  "ham":["I like ham and cheese.","나는 햄과 치즈를 좋아해요.","and로 명사 연결."],
  "corn":["Corn is yellow.","옥수수는 노래요.","corn은 셀 수 없는 명사."],
  "bean":["Beans are good for health.","콩은 건강에 좋아요.","'be good for ~'는 ~에 좋다."],
  "nut":["Squirrels eat nuts.","다람쥐는 견과를 먹어요.","복수 nuts."],
  "salt":["Add a little salt.","소금을 조금 넣어요.","'a little'은 약간(셀 수 없는 명사)."],
  "sugar":["I don't take sugar in my coffee.","나는 커피에 설탕을 안 넣어요.","부정문."],
  "oil":["Cook it in oil.","기름에 요리해요.","'in oil'은 기름에."],
  "tea":["Would you like some tea?","차 좀 드시겠어요?","'Would you like ~?'는 권유."],
  "juice":["I drink orange juice.","나는 오렌지 주스를 마셔요.","현재시제."],
  "beef":["This beef is delicious.","이 소고기는 맛있어요.","'be + 형용사'."],
  "pork":["We had pork for dinner.","우리는 저녁으로 돼지고기를 먹었어요.","과거시제(have→had)."],
  "fruit":["Eat more fruit.","과일을 더 먹어요.","more는 더 많은."],
  "grape":["Grapes are sweet.","포도는 달아요.","복수 grapes."],
  "peach":["This peach is juicy.","이 복숭아는 즙이 많아요.","형용사 juicy."],
  "pear":["A pear is bigger than an apple.","배는 사과보다 커요.","비교급 'bigger than'."],
  "plum":["The plum is purple.","자두는 보라색이에요.","'be + 형용사'."],
  "lemon":["A lemon is sour.","레몬은 셔요.","형용사 sour."],
  "melon":["This melon smells sweet.","이 멜론은 달콤한 냄새가 나요.","'smell + 형용사'는 ~한 냄새가 나다."],
  "berry":["Birds eat berries.","새는 베리를 먹어요.","berry의 복수는 berries."],
  "onion":["Onions make me cry.","양파는 나를 울려요.","'make + 목적어 + 동사원형'(5형식)."],
  "potato":["I like baked potatoes.","나는 구운 감자를 좋아해요.","potato의 복수는 potatoes."],
  "tomato":["A tomato is red and round.","토마토는 빨갛고 둥글어요.","and로 형용사 연결."],
  "carrot":["Rabbits love carrots.","토끼는 당근을 좋아해요.","복수 carrots."],
  "garlic":["Korean food uses a lot of garlic.","한국 음식은 마늘을 많이 써요.","'a lot of'는 많은."],
  "pepper":["Add some pepper.","후추를 좀 넣어요.","some은 약간의."],
  "candy":["Kids love candy.","아이들은 사탕을 좋아해요.","candy는 보통 셀 수 없는 명사."],
  "cookie":["I baked some cookies.","나는 쿠키를 좀 구웠어요.","과거시제 baked."],
  "honey":["Bees make honey.","벌은 꿀을 만들어요.","현재시제."],
  "butter":["Spread butter on the bread.","빵에 버터를 발라요.","'on the bread'는 빵에."],
  "cheese":["I like cheese on my pizza.","나는 피자에 치즈를 좋아해요.","'on my pizza'는 피자에."],
  "bacon":["I had bacon and eggs.","나는 베이컨과 달걀을 먹었어요.","과거시제 had."],
  "flour":["Mix the flour with water.","밀가루를 물과 섞어요.","'mix A with B'는 A를 B와 섞다."],
  "pasta":["I cooked pasta for dinner.","나는 저녁으로 파스타를 만들었어요.","과거시제 cooked."],
  "steak":["He likes his steak well-done.","그는 스테이크를 바싹 익힌 걸 좋아해요.","well-done은 바싹 익힌."],
  "donut":["I ate a chocolate donut.","나는 초콜릿 도넛을 먹었어요.","과거시제 ate."],
  "burger":["I ordered a cheese burger.","나는 치즈버거를 주문했어요.","과거시제 ordered."],
  "cream":["Add cream to the soup.","수프에 크림을 넣어요.","'add A to B'는 B에 A를 넣다."],
  "soda":["I drink too much soda.","나는 탄산음료를 너무 많이 마셔요.","'too much'는 너무 많은(셀 수 없는 명사)."],
  "salad":["I had a green salad.","나는 그린 샐러드를 먹었어요.","과거시제 had."],
  "snack":["Let's have a snack.","간식 먹자.","'have a snack'은 간식을 먹다."],
  "meal":["We had a big meal.","우리는 푸짐한 식사를 했어요.","형용사 big."],
  "kiwi":["A kiwi is green inside.","키위는 속이 초록색이에요.","inside는 부사(안쪽은)."],
  "mango":["Mangoes are sweet and soft.","망고는 달고 부드러워요.","mango의 복수는 mangoes."],
  "cloud":["There are white clouds in the sky.","하늘에 흰 구름이 있어요.","'There are + 복수'."],
  "wave":["The waves are big today.","오늘 파도가 커요.","복수 waves라 are."],
  "sand":["The sand is warm.","모래가 따뜻해요.","sand는 셀 수 없는 명사."],
  "rock":["He sat on a big rock.","그는 큰 바위에 앉았어요.","과거시제(sit→sat)."],
  "stone":["She threw a stone into the water.","그녀는 물에 돌을 던졌어요.","과거시제(throw→threw)."],
  "hill":["We walked up the hill.","우리는 언덕을 올라갔어요.","'up the hill'은 언덕 위로."],
  "lake":["We swam in the lake.","우리는 호수에서 수영했어요.","과거시제(swim→swam)."],
  "pond":["Ducks swim in the pond.","오리가 연못에서 헤엄쳐요.","'in the pond'."],
  "grass":["The grass is green.","잔디가 푸르러요.","grass는 셀 수 없는 명사."],
  "leaf":["The leaves fall in autumn.","가을에 잎이 떨어져요.","leaf의 복수는 leaves."],
  "seed":["Plant the seeds in spring.","봄에 씨앗을 심어요.","'in spring'은 봄에."],
  "wood":["The table is made of wood.","탁자는 나무로 만들어졌어요.","'be made of ~'는 ~로 만들어지다."],
  "gold":["This ring is made of gold.","이 반지는 금으로 만들어졌어요.","'be made of ~'."],
  "coal":["We burn coal for heat.","우리는 열을 위해 석탄을 태워요.","'for heat'은 열을 위해."],
  "mud":["The pig plays in the mud.","돼지가 진흙에서 놀아요.","'in the mud'는 진흙에서."],
  "dust":["There is dust on the shelf.","선반에 먼지가 있어요.","'There is + 셀 수 없는 명사'."],
  "fog":["The fog is thick this morning.","오늘 아침 안개가 짙어요.","형용사 thick."],
  "frost":["There was frost on the window.","창문에 서리가 끼었어요.","과거시제(there was)."],
  "flood":["The flood damaged the town.","홍수가 마을을 망가뜨렸어요.","과거시제 damaged."],
  "dawn":["We woke up at dawn.","우리는 새벽에 일어났어요.","'at dawn'은 새벽에."],
  "noon":["Let's meet at noon.","정오에 만나자.","'at noon'은 정오에."],
  "week":["I work five days a week.","나는 일주일에 닷새 일해요.","'a week'은 일주일에."],
  "year":["A year has twelve months.","일 년은 열두 달이에요.","숫자 twelve."],
  "month":["There are thirty days in a month.","한 달은 삼십 일이에요.","'in a month'는 한 달에."],
  "hole":["There is a hole in my sock.","내 양말에 구멍이 있어요.","'in my sock'은 양말에."],
  "cave":["Bats live in the cave.","박쥐는 동굴에 살아요.","'in the cave'."],
  "cliff":["Be careful near the cliff.","절벽 근처에서 조심해요.","'near the cliff'는 절벽 근처에서."],
  "shore":["We walked along the shore.","우리는 해안을 따라 걸었어요.","'along the shore'는 해안을 따라."],
  "coast":["The city is on the east coast.","그 도시는 동해안에 있어요.","'on the coast'는 해안에."],
  "branch":["A bird sat on the branch.","새가 나뭇가지에 앉았어요.","'on the branch'."],
  "bush":["A cat hid behind the bush.","고양이가 덤불 뒤에 숨었어요.","과거시제(hide→hid)."],
  "valley":["The river flows through the valley.","강이 계곡을 통해 흘러요.","'through the valley'는 계곡을 통해."],
  "desert":["It is very hot in the desert.","사막은 매우 더워요.","비인칭 주어 it."],
  "jungle":["Many animals live in the jungle.","많은 동물이 정글에 살아요.","'in the jungle'."],
  "swamp":["Crocodiles live in the swamp.","악어는 늪에 살아요.","'in the swamp'."],
  "fin":["A fish swims with its fins.","물고기는 지느러미로 헤엄쳐요.","'with + 도구'."],
  "shell":["I found a shell on the beach.","나는 해변에서 조개껍데기를 찾았어요.","과거시제(find→found)."],
  "pearl":["The necklace has white pearls.","그 목걸이에는 흰 진주가 있어요.","복수 pearls."],
  "reef":["Colorful fish live near the reef.","알록달록한 물고기가 암초 근처에 살아요.","'near the reef'."],
  "tide":["The tide comes in at night.","밀물은 밤에 들어와요.","'come in'은 밀려들다."],
  "rainbow":["I see a rainbow after the rain.","비가 온 뒤 무지개가 보여요.","'after the rain'은 비가 온 뒤."],
  "comet":["A comet has a long tail.","혜성은 긴 꼬리가 있어요.","형용사 long."],
  "heat":["I can't stand the summer heat.","나는 여름 더위를 못 견뎌요.","'can't stand'은 못 견디다."],
  "mist":["Morning mist covers the hills.","아침 안개가 언덕을 덮어요.","3인칭 단수 covers."],
  "hail":["Hail fell from the sky.","우박이 하늘에서 떨어졌어요.","과거시제(fall→fell)."],
  "breeze":["A cool breeze feels nice.","시원한 산들바람이 기분 좋아요.","'feel + 형용사'."],
  "smoke":["Smoke rises from the chimney.","연기가 굴뚝에서 올라와요.","3인칭 단수 rises."],
  "flame":["The candle flame is small.","촛불의 불꽃이 작아요.","형용사 small."],
  "spark":["A spark started the fire.","불꽃이 불을 일으켰어요.","과거시제 started."],
  "ash":["Gray ash covered the ground.","회색 재가 땅을 덮었어요.","과거시제 covered."],
  "steam":["Steam rises from hot soup.","뜨거운 수프에서 김이 올라와요.","3인칭 단수 rises."],
  "bubble":["Children love soap bubbles.","아이들은 비눗방울을 좋아해요.","복수 bubbles."],
  "drop":["A drop of water fell.","물 한 방울이 떨어졌어요.","'a drop of ~'는 한 방울의."],
  "north":["Birds fly north in summer.","새는 여름에 북쪽으로 날아가요.","north는 부사(북쪽으로)."],
  "south":["It is warmer in the south.","남쪽이 더 따뜻해요.","비교급 warmer."],
  "east":["The sun rises in the east.","해는 동쪽에서 떠요.","'in the east'."],
  "west":["The sun sets in the west.","해는 서쪽으로 져요.","3인칭 단수 sets."],
  "left":["Turn left at the corner.","모퉁이에서 왼쪽으로 도세요.","명령문. left는 부사."],
  "right":["The store is on your right.","가게는 당신 오른쪽에 있어요.","'on your right'."],
  "world":["I want to travel the world.","나는 세계를 여행하고 싶어요.","'want to + 동사원형'."],
  "land":["The plane landed on the land.","비행기가 땅에 착륙했어요.","과거시제 landed."],
  "floor":["The keys are on the floor.","열쇠가 바닥에 있어요.","'on the floor'."],
  "stair":["Be careful on the stairs.","계단에서 조심해요.","stairs는 보통 복수로."],
  "step":["Watch your step.","발밑을 조심해요.","'watch your step'은 발밑 조심."],
  "stick":["The dog likes to fetch a stick.","개는 막대기 물어오는 걸 좋아해요.","'like to + 동사원형'."],
  "brick":["The house is made of brick.","그 집은 벽돌로 지어졌어요.","'be made of ~'."],
  "chain":["The dog is on a chain.","개가 사슬에 묶여 있어요.","'on a chain'."],
  "hook":["Hang your coat on the hook.","코트를 고리에 걸어요.","'on the hook'."],
  "lock":["Put a lock on the door.","문에 자물쇠를 채워요.","'on the door'."],
  "clay":["We made pots from clay.","우리는 점토로 그릇을 만들었어요.","'from clay'는 점토로."],
  "town":["I live in a small town.","나는 작은 마을에 살아요.","'in a small town'."],
  "city":["Seoul is a big city.","서울은 큰 도시예요.","'a big city'."],
  "edge":["Don't stand near the edge.","가장자리 근처에 서지 마세요.","부정 명령문."],
  "end":["We are near the end of the road.","우리는 길 끝 가까이 있어요.","'the end of ~'는 ~의 끝."],
  "room":["My room is small but cozy.","내 방은 작지만 아늑해요.","but은 대조 접속사."],
  "wall":["There is a picture on the wall.","벽에 그림이 있어요.","'on the wall'."],
  "roof":["A cat is on the roof.","고양이가 지붕 위에 있어요.","'on the roof'."],
  "gate":["Close the gate, please.","문을 닫아 주세요.","명령문."],
  "desk":["My books are on the desk.","내 책이 책상 위에 있어요.","'on the desk'."],
  "lamp":["Turn on the lamp.","램프를 켜요.","'turn on'은 켜다."],
  "fork":["Eat with a fork.","포크로 먹어요.","'with a fork'."],
  "dish":["Wash the dishes.","설거지를 해요.","'wash the dishes'는 설거지하다."],
  "bowl":["I ate a bowl of rice.","나는 밥 한 그릇을 먹었어요.","'a bowl of ~'는 한 그릇의."],
  "glass":["Pour water into the glass.","유리잔에 물을 따라요.","'into the glass'."],
  "jar":["The jam is in a jar.","잼이 병에 들어 있어요.","'in a jar'."],
  "pot":["Boil the water in a pot.","냄비에 물을 끓여요.","'in a pot'."],
  "pan":["Fry the egg in a pan.","팬에 달걀을 부쳐요.","'in a pan'."],
  "soap":["Wash your hands with soap.","비누로 손을 씻어요.","'with soap'."],
  "comb":["Comb your hair.","머리를 빗어요.","comb는 동사로도 쓰여요(빗다)."],
  "brush":["I brush my teeth twice a day.","나는 하루에 두 번 이를 닦아요.","'twice a day'는 하루에 두 번."],
  "broom":["Sweep the floor with a broom.","빗자루로 바닥을 쓸어요.","'with a broom'."],
  "rope":["Pull the rope hard.","밧줄을 세게 당겨요.","hard는 부사(세게)."],
  "tape":["Fix it with tape.","테이프로 그것을 고쳐요.","'with tape'."],
  "glue":["Stick the paper with glue.","풀로 종이를 붙여요.","'with glue'."],
  "bell":["The bell rings at noon.","종이 정오에 울려요.","3인칭 단수 rings."],
  "drum":["He plays the drums.","그는 드럼을 쳐요.","악기 앞에는 the."],
  "kite":["We flew a kite in the park.","우리는 공원에서 연을 날렸어요.","과거시제(fly→flew)."],
  "doll":["The girl loves her doll.","그 소녀는 인형을 좋아해요.","소유격 her."],
  "toy":["The baby plays with toys.","아기가 장난감을 가지고 놀아요.","'play with ~'는 ~을 가지고 놀다."],
  "ring":["She wears a gold ring.","그녀는 금반지를 껴요.","현재시제 wears."],
  "coin":["I have some coins in my pocket.","주머니에 동전이 좀 있어요.","'in my pocket'."],
  "frame":["Put the photo in a frame.","사진을 액자에 넣어요.","'in a frame'."],
  "shelf":["The books are on the shelf.","책이 선반에 있어요.","shelf의 복수는 shelves."],
  "drawer":["Open the top drawer.","맨 위 서랍을 열어요.","top은 맨 위의."],
  "closet":["Hang the clothes in the closet.","옷을 옷장에 걸어요.","'in the closet'."],
  "pillow":["This pillow is soft.","이 베개는 부드러워요.","'be + 형용사'."],
  "blanket":["Cover yourself with a blanket.","담요로 몸을 덮어요.","'with a blanket'."],
  "sheet":["Change the bed sheets.","침대 시트를 갈아요.","복수 sheets."],
  "curtain":["Open the curtains.","커튼을 열어요.","복수 curtains."],
  "carpet":["The carpet is soft and warm.","카펫이 부드럽고 따뜻해요.","and로 형용사 연결."],
  "fan":["Turn on the fan.","선풍기를 켜요.","'turn on'."],
  "oven":["Bake the cake in the oven.","오븐에 케이크를 구워요.","'in the oven'."],
  "sink":["Wash the dishes in the sink.","싱크대에서 설거지를 해요.","'in the sink'."],
  "tub":["The baby is in the tub.","아기가 욕조에 있어요.","'in the tub'."],
  "stove":["Cook on the stove.","난로에서 요리해요.","'on the stove'."],
  "hut":["They live in a small hut.","그들은 작은 오두막에 살아요.","'in a small hut'."],
  "tent":["We slept in a tent.","우리는 텐트에서 잤어요.","과거시제(sleep→slept)."],
  "cart":["Push the shopping cart.","쇼핑 카트를 밀어요.","명령문."],
  "sled":["Kids ride sleds in winter.","아이들은 겨울에 썰매를 타요.","'in winter'."],
  "horn":["The car horn is loud.","자동차 경적이 시끄러워요.","형용사 loud."],
  "flute":["She plays the flute well.","그녀는 플루트를 잘 불어요.","well은 부사."],
  "cube":["Add an ice cube.","얼음 한 조각을 넣어요.","'ice cube'는 얼음 조각."],
  "cap":["He wears a baseball cap.","그는 야구 모자를 써요.","현재시제 wears."],
  "coat":["Put on your coat.","코트를 입어요.","'put on'은 입다."],
  "shirt":["This shirt is too big.","이 셔츠는 너무 커요.","'too + 형용사'."],
  "skirt":["She is wearing a blue skirt.","그녀는 파란 치마를 입고 있어요.","현재진행형."],
  "dress":["What a pretty dress!","정말 예쁜 드레스다!","감탄문 'What a + 형용사 + 명사!'."],
  "sock":["I can't find my socks.","양말을 못 찾겠어요.","복수 socks."],
  "shoe":["Tie your shoes.","신발 끈을 묶어요.","복수 shoes."],
  "boot":["Wear your boots in the snow.","눈에서는 부츠를 신어요.","복수 boots."],
  "glove":["Put on your gloves.","장갑을 껴요.","복수 gloves."],
  "scarf":["She wears a warm scarf.","그녀는 따뜻한 목도리를 둘러요.","형용사 warm."],
  "belt":["Fasten your belt.","벨트를 매요.","'fasten'은 매다."],
  "jeans":["I wear blue jeans every day.","나는 매일 청바지를 입어요.","jeans는 항상 복수."],
  "pants":["These pants are too long.","이 바지는 너무 길어요.","pants는 항상 복수라 these/are."],
  "vest":["He wears a vest over his shirt.","그는 셔츠 위에 조끼를 입어요.","'over ~'는 ~위에."],
  "robe":["She put on a bath robe.","그녀는 목욕 가운을 입었어요.","과거시제(put은 동일형)."],
  "tie":["He wears a tie to work.","그는 회사에 넥타이를 매고 가요.","'to work'는 회사에."],
  "cloth":["Clean it with a wet cloth.","젖은 천으로 그것을 닦아요.","형용사 wet."],
  "bike":["I ride my bike to school.","나는 자전거를 타고 학교에 가요.","'ride a bike'는 자전거를 타다."],
  "train":["I take the train every morning.","나는 매일 아침 기차를 타요.","'take the train'."],
  "truck":["The truck carries boxes.","트럭이 상자를 날라요.","3인칭 단수 carries."],
  "boat":["We rowed the boat across the lake.","우리는 호수를 가로질러 배를 저었어요.","과거시제 rowed."],
  "jet":["A jet flies very fast.","제트기는 매우 빨리 날아요.","fast는 부사."],
  "taxi":["Let's take a taxi.","택시를 타자.","'take a taxi'."],
  "van":["The van is full of boxes.","밴이 상자로 가득해요.","'full of ~'는 ~로 가득한."],
  "cab":["I called a cab.","나는 택시를 불렀어요.","과거시제 called."],
  "plane":["The plane takes off at six.","비행기가 6시에 이륙해요.","'take off'는 이륙하다."],
  "wheel":["A car has four wheels.","자동차는 바퀴가 네 개예요.","수 four."],
  "sail":["The boat has a white sail.","그 배는 흰 돛이 있어요.","형용사 white."],
  "subway":["I go to work by subway.","나는 지하철로 출근해요.","'by subway'는 지하철로."],
  "one":["I have only one brother.","나는 형이 한 명뿐이에요.","only는 ~만."],
  "two":["I have two cats.","나는 고양이 두 마리가 있어요.","복수 cats."],
  "three":["The movie starts in three minutes.","영화가 3분 후에 시작해요.","'in three minutes'는 3분 후에."],
  "four":["A table has four legs.","탁자는 다리가 네 개예요.","수 four."],
  "five":["I wake up at five.","나는 5시에 일어나요.","'at five'."],
  "six":["School ends at six.","학교는 6시에 끝나요.","3인칭 단수 ends."],
  "seven":["There are seven days in a week.","일주일은 칠 일이에요.","'There are + 복수'."],
  "eight":["A spider has eight legs.","거미는 다리가 여덟 개예요.","수 eight."],
  "nine":["The store opens at nine.","가게는 9시에 열어요.","3인칭 단수 opens."],
  "ten":["I have ten fingers.","나는 손가락이 열 개예요.","수 ten."],
  "zero":["The temperature is below zero.","기온이 영하예요.","'below zero'는 영하."],
  "gray":["The sky is gray today.","오늘 하늘이 회색이에요.","'be + 형용사'."],
  "brown":["She has brown eyes.","그녀는 갈색 눈을 가졌어요.","형용사 brown."],
  "silver":["I bought a silver ring.","나는 은반지를 샀어요.","과거시제 bought."],
  "tan":["His skin is tan.","그의 피부는 황갈색이에요.","'be + 형용사'."],
  "navy":["She wears a navy jacket.","그녀는 남색 재킷을 입어요.","형용사 navy."],
  "baby":["The baby is sleeping.","아기가 자고 있어요.","현재진행형."],
  "boy":["The boy is playing soccer.","소년이 축구를 하고 있어요.","현재진행형."],
  "girl":["The girl sings beautifully.","소녀가 아름답게 노래해요.","beautifully는 부사."],
  "man":["The man is reading a newspaper.","남자가 신문을 읽고 있어요.","현재진행형."],
  "woman":["The woman is a doctor.","그 여자는 의사예요.","'be + 직업'."],
  "kid":["The kids are playing outside.","아이들이 밖에서 놀고 있어요.","복수 kids."],
  "son":["Their son is ten years old.","그들의 아들은 열 살이에요.","'~ years old'는 ~살."],
  "aunt":["My aunt lives in Busan.","우리 이모는 부산에 살아요.","3인칭 단수 lives."],
  "uncle":["My uncle is very kind.","우리 삼촌은 매우 친절해요.","'be + 형용사'."],
  "mom":["My mom makes great food.","우리 엄마는 음식을 잘 만들어요.","3인칭 단수 makes."],
  "dad":["My dad drives a truck.","우리 아빠는 트럭을 몰아요.","3인칭 단수 drives."],
  "child":["The child is very smart.","그 아이는 아주 똑똑해요.","child의 복수는 children."],
  "adult":["This movie is for adults.","이 영화는 어른용이에요.","'for adults'는 어른용."],
  "lady":["The lady is wearing a hat.","그 숙녀는 모자를 쓰고 있어요.","현재진행형."],
  "hero":["He is my hero.","그는 내 영웅이에요.","소유격 my."],
  "queen":["The queen lives in a palace.","여왕은 궁전에 살아요.","'in a palace'."],
  "prince":["The prince married a princess.","왕자는 공주와 결혼했어요.","과거시제 married."],
  "twin":["She has a twin sister.","그녀는 쌍둥이 자매가 있어요.","형용사처럼 쓰인 twin."],
  "nurse":["The nurse helps the doctor.","간호사가 의사를 도와요.","3인칭 단수 helps."],
  "pet":["Do you have a pet?","애완동물 키우세요?","의문문 'Do you ~?'."],
  "word":["What does this word mean?","이 단어는 무슨 뜻이에요?","'What does ~ mean?'은 무슨 뜻이냐."],
  "line":["Draw a straight line.","직선을 그어요.","형용사 straight."],
  "page":["Open your book to page ten.","책 10쪽을 펴요.","'to page ten'은 10쪽을."],
  "note":["I left you a note.","너에게 메모를 남겼어.","과거시제(leave→left)."],
  "song":["This is my favorite song.","이건 내가 가장 좋아하는 노래예요.","favorite은 가장 좋아하는."],
  "game":["Let's play a game.","게임 하자.","'play a game'."],
  "team":["Our team won the match.","우리 팀이 경기에서 이겼어요.","과거시제(win→won)."],
  "wish":["Make a wish!","소원을 빌어요!","'make a wish'는 소원을 빌다."],
  "joke":["He told a funny joke.","그는 재미있는 농담을 했어요.","과거시제(tell→told)."],
  "story":["Tell me a story.","이야기를 들려줘.","'tell + 사람 + 사물'(4형식)."],
  "dream":["My dream is to be a pilot.","내 꿈은 조종사가 되는 거예요.","'to be ~'는 ~이 되는 것."],
  "smile":["She has a lovely smile.","그녀는 사랑스러운 미소를 지녔어요.","형용사 lovely."],
  "tear":["Tears ran down her face.","눈물이 그녀의 얼굴에 흘러내렸어요.","과거시제(run→ran)."],
  "kiss":["She gave him a kiss.","그녀는 그에게 키스를 했어요.","'give + 사람 + 사물'(4형식)."],
  "hug":["Give me a hug.","나를 안아 줘.","'give a hug'는 안아주다."],
  "gift":["This is a gift for you.","이건 너를 위한 선물이야.","'for you'는 너를 위한."],
  "news":["The news is very sad.","그 소식은 매우 슬퍼요.","news는 단수 취급(is)."],
  "fact":["That is a well-known fact.","그것은 잘 알려진 사실이에요.","well-known은 잘 알려진."],
  "idea":["That is a great idea.","그거 정말 좋은 생각이에요.","형용사 great."],
  "plan":["Do you have a plan?","계획이 있어요?","의문문."],
  "rule":["Follow the rules.","규칙을 따라요.","복수 rules."],
  "fun":["We had a lot of fun.","우리는 정말 즐거웠어요.","'a lot of fun'은 큰 재미."],
  "job":["She has a good job.","그녀는 좋은 직업을 가졌어요.","형용사 good."],
  "shop":["The shop opens at nine.","가게는 9시에 열어요.","3인칭 단수 opens."],
  "store":["I bought it at the store.","나는 가게에서 그것을 샀어요.","'at the store'."],
  "park":["Let's walk in the park.","공원에서 산책하자.","'in the park'."],
  "zoo":["We saw lions at the zoo.","우리는 동물원에서 사자를 봤어요.","과거시제(see→saw)."],
  "farm":["They grow corn on the farm.","그들은 농장에서 옥수수를 길러요.","'on the farm'."],
  "bank":["I went to the bank.","나는 은행에 갔어요.","과거시제(go→went)."],
  "mall":["Let's meet at the mall.","쇼핑몰에서 만나자.","'at the mall'."],
  "path":["Follow this path to the lake.","호수까지 이 길을 따라가요.","'to the lake'는 호수까지."],
  "yard":["The kids play in the yard.","아이들이 마당에서 놀아요.","'in the yard'."],
  "flag":["The flag is red and blue.","그 깃발은 빨간색과 파란색이에요.","and로 색 연결."],
  "sit":["Please sit down here.","여기 앉으세요.","'sit down'은 앉다."],
  "stand":["Stand up, please.","일어서 주세요.","'stand up'은 일어서다."],
  "find":["I can't find my keys.","열쇠를 못 찾겠어요.","'can't + 동사원형'."],
  "call":["Call me tonight.","오늘 밤에 전화해.","명령문. call은 전화하다·부르다."],
  "turn":["Turn off the light.","불을 꺼요.","'turn off'는 끄다."],
  "stop":["Stop the car!","차를 멈춰요!","명령문."],
  "wait":["Wait for me.","나를 기다려 줘.","'wait for ~'는 ~을 기다리다."],
  "push":["Push the door open.","문을 밀어서 열어요.","'push ~ open'은 밀어서 열다."],
  "pull":["Pull the rope.","밧줄을 당겨요.","명령문."],
  "hold":["Hold my hand.","내 손을 잡아요.","명령문."],
  "keep":["Keep the change.","거스름돈은 가지세요.","keep은 가지다·유지하다."],
  "put":["Put it on the table.","그것을 탁자에 놓아요.","'put + 목적어 + 장소'."],
  "cut":["Cut the paper in half.","종이를 반으로 잘라요.","'in half'는 반으로."],
  "pay":["I will pay for lunch.","점심값은 내가 낼게.","'pay for ~'는 ~값을 내다."],
  "win":["I hope we win the game.","우리가 경기에서 이기길 바라요.","'hope + 문장'."],
  "move":["Don't move!","움직이지 마!","부정 명령문."],
  "show":["Show me the way.","길을 알려줘.","'show + 사람 + 사물'(4형식)."],
  "tell":["Tell me the truth.","나에게 진실을 말해.","'tell + 사람 + 사물'(4형식)."],
  "ask":["May I ask a question?","질문 하나 해도 될까요?","'May I ~?'는 ~해도 될까요."],
  "try":["Try your best.","최선을 다해요.","'try one's best'는 최선을 다하다."],
  "use":["Can I use your phone?","전화 좀 써도 될까요?","'Can I ~?'."],
  "feel":["I feel happy today.","오늘 기분이 좋아요.","'feel + 형용사'."],
  "grow":["Plants grow in the sun.","식물은 햇빛에서 자라요.","현재시제(일반적 사실)."],
  "send":["Send me an email.","나에게 이메일을 보내.","'send + 사람 + 사물'(4형식)."],
  "bring":["Bring your umbrella.","우산을 가져와요.","명령문."],
  "catch":["Catch the ball!","공을 잡아요!","명령문."],
  "throw":["Don't throw stones.","돌을 던지지 마요.","부정 명령문."],
  "wet":["My clothes are wet.","내 옷이 젖었어요.","'be + 형용사'."],
  "dry":["The towel is dry now.","수건이 이제 말랐어요.","'be + 형용사'."],
  "full":["The cup is full of water.","컵이 물로 가득해요.","'full of ~'는 ~로 가득한."],
  "empty":["The box is empty.","상자가 비어 있어요.","'be + 형용사'."],
  "rich":["He is a rich man.","그는 부유한 사람이에요.","형용사 rich."],
  "poor":["They were very poor.","그들은 매우 가난했어요.","과거시제(were)."],
  "soft":["The pillow is soft.","베개가 부드러워요.","'be + 형용사'."],
  "loud":["The music is too loud.","음악이 너무 시끄러워요.","'too + 형용사'."],
  "quiet":["Please be quiet.","조용히 해 주세요.","'be + 형용사' 명령문."],
  "deep":["The river is very deep.","강이 매우 깊어요.","'be + 형용사'."],
  "wide":["The road is wide.","길이 넓어요.","'be + 형용사'."],
  "thin":["The ice is too thin.","얼음이 너무 얇아요.","'too + 형용사'."],
  "thick":["This book is very thick.","이 책은 매우 두꺼워요.","'be + 형용사'."],
  "heavy":["This box is too heavy.","이 상자는 너무 무거워요.","'too + 형용사'."],
  "round":["The earth is round.","지구는 둥글어요.","'be + 형용사'."],
  "flat":["The road is flat and straight.","길이 평평하고 곧아요.","and로 형용사 연결."],
  "sharp":["This knife is very sharp.","이 칼은 매우 날카로워요.","'be + 형용사'."],
  "safe":["You are safe now.","이제 안전해요.","'be + 형용사'."],
  "free":["Are you free tonight?","오늘 밤 한가해요?","free는 한가한·자유로운·무료의."],
  "busy":["I am too busy today.","나는 오늘 너무 바빠요.","'too + 형용사'."],
  "lazy":["Don't be so lazy.","그렇게 게으르지 마.","'be + 형용사' 부정 명령문."],
  "brave":["She is a brave girl.","그녀는 용감한 소녀예요.","형용사 brave."],
  "shy":["He is too shy to speak.","그는 너무 수줍어서 말을 못해요.","'too ~ to …'는 너무 ~해서 …못하다."],
  "proud":["I am proud of you.","나는 네가 자랑스러워.","'be proud of ~'는 ~을 자랑스러워하다."],
  "calm":["Stay calm.","침착해요.","'stay + 형용사'는 ~한 상태를 유지하다."],
  "wise":["She is a wise woman.","그녀는 현명한 여자예요.","형용사 wise."],
  "fair":["That is not fair.","그건 공평하지 않아요.","부정문 'is not'."],
  "true":["Is it true?","그게 사실이에요?","의문문."],
  "real":["Is this a real diamond?","이거 진짜 다이아몬드예요?","형용사 real."],
  "same":["We are in the same class.","우리는 같은 반이에요.","'the same ~'은 같은 ~."],
  "close":["Close the window.","창문을 닫아요.","명령문. close는 닫다."],
  "fall":["Leaves fall in autumn.","가을에 잎이 떨어져요.","현재시제(일반적 사실)."],
  "fly":["Birds fly in the sky.","새는 하늘에서 날아요.","현재시제."],
  "ride":["I ride my bike to school.","나는 자전거를 타고 학교에 가요.","'ride a bike'."],
  "drive":["She drives to work.","그녀는 차로 출근해요.","3인칭 단수 drives."],
  "cook":["My dad cooks dinner.","우리 아빠가 저녁을 요리해요.","3인칭 단수 cooks."],
  "wash":["Wash your hands.","손을 씻어요.","명령문."],
  "add":["Add two and three.","2와 3을 더해요.","add는 더하다."],
  "count":["Count from one to ten.","1부터 10까지 세요.","'from A to B'."],
  "draw":["I like to draw pictures.","나는 그림 그리는 걸 좋아해요.","'like to + 동사원형'."],
  "kick":["Kick the ball hard.","공을 세게 차요.","hard는 부사."],
  "clap":["Let's clap our hands.","손뼉을 치자.","'clap hands'는 손뼉치다."],
  "fresh":["These vegetables are fresh.","이 채소들은 신선해요.","복수 주어라 are."],
  "sweet":["This cake is too sweet.","이 케이크는 너무 달아요.","'too + 형용사'."],
  "sour":["The lemon tastes sour.","레몬은 신맛이 나요.","'taste + 형용사'는 ~한 맛이 나다."],
  "salty":["The soup is too salty.","수프가 너무 짜요.","'too + 형용사'."],
  "spicy":["Korean food is often spicy.","한국 음식은 자주 매워요.","often은 자주(빈도부사)."],
  "tiny":["A baby has tiny hands.","아기는 아주 작은 손을 가졌어요.","형용사 tiny."],
  "huge":["They live in a huge house.","그들은 거대한 집에 살아요.","형용사 huge."],
  "pie":["I baked an apple pie.","나는 사과 파이를 구웠어요.","과거시제 baked."],
  "chip":["I love potato chips.","나는 감자칩을 좋아해요.","복수 chips."],
  "raft":["We crossed the river on a raft.","우리는 뗏목으로 강을 건넜어요.","과거시제 crossed."],
  "ferry":["We took a ferry to the island.","우리는 섬까지 페리를 탔어요.","과거시제(take→took)."],
  "stream":["A small stream runs through the woods.","작은 개울이 숲을 가로질러 흘러요.","3인칭 단수 runs."],
  "earth":["The earth goes around the sun.","지구는 태양 주위를 돌아요.","'go around ~'는 ~주위를 돌다."],
  "ocean":["The ocean is deep and blue.","바다는 깊고 푸르러요.","and로 형용사 연결."],
  "planet":["Earth is our planet.","지구는 우리 행성이에요.","소유격 our."],
  "pin":["Be careful with the pin.","핀을 조심해요.","'be careful with ~'."],
  "needle":["Thread the needle.","바늘에 실을 꿰어요.","thread는 동사(실을 꿰다)."],
  "thread":["I need a needle and thread.","나는 바늘과 실이 필요해요.","and로 명사 연결."],
  "mat":["Wipe your feet on the mat.","매트에 발을 닦아요.","'on the mat'."],
  "vase":["Put the flowers in the vase.","꽃을 꽃병에 꽂아요.","'in the vase'."],
  "watch":["I bought a new watch.","나는 새 시계를 샀어요.","watch는 손목시계·보다."],
  "cousin":["My cousin lives in Canada.","내 사촌은 캐나다에 살아요.","3인칭 단수 lives."],
  "niece":["My niece is five years old.","내 조카딸은 다섯 살이에요.","'~ years old'."],
  "nephew":["I bought a gift for my nephew.","나는 조카를 위해 선물을 샀어요.","'for ~'는 ~을 위해."],
  "pony":["The girl rides a pony.","소녀가 조랑말을 타요.","3인칭 단수 rides."],
  "moth":["A moth flew to the light.","나방이 불빛으로 날아갔어요.","과거시제(fly→flew)."],
  "clam":["We dug for clams on the beach.","우리는 해변에서 조개를 캤어요.","과거시제(dig→dug)."],
  "green":["The grass is green.","잔디는 초록색이에요.","'be + 형용사'."],
  "white":["She wore a white dress.","그녀는 흰 드레스를 입었어요.","과거시제(wear→wore)."],
  "black":["He has black hair.","그는 검은 머리를 가졌어요.","형용사 black."],
  "warm":["The water is warm.","물이 따뜻해요.","'be + 형용사'."],
  "swim":["I can swim very well.","나는 수영을 아주 잘해요.","조동사 can + 동사원형."],
  "look":["Look at the moon.","달을 봐요.","'look at ~'은 ~을 보다."],
  "talk":["Let's talk later.","나중에 얘기하자.","later는 부사(나중에)."],
  "red":["Roses are red.","장미는 빨개요.","복수 주어라 are."],
  "blue":["The sky is blue.","하늘은 파래요.","'be + 형용사'."],
  "yellow":["The banana is yellow.","바나나는 노래요.","'be + 형용사'."],
  "pink":["She likes pink flowers.","그녀는 분홍 꽃을 좋아해요.","형용사 pink."],
  "kind":["She is very kind to me.","그녀는 나에게 매우 친절해요.","'kind to ~'는 ~에게 친절한."],
  "nice":["Have a nice day!","좋은 하루 보내요!","형용사 nice."],
  "sad":["Why are you so sad?","왜 그렇게 슬퍼요?","'so + 형용사'."],
  "easy":["This test is easy.","이 시험은 쉬워요.","'be + 형용사'."],
  "hard":["This question is too hard.","이 문제는 너무 어려워요.","hard는 어려운·단단한."],
  "dark":["It is getting dark.","어두워지고 있어요.","'get + 형용사'는 ~해지다."],
  "light":["The room is bright and light.","방이 밝고 환해요.","light는 밝은·가벼운."],
  "dirty":["Your hands are dirty.","손이 더러워요.","복수 주어라 are."],
  "young":["She looks young.","그녀는 어려 보여요.","'look + 형용사'."],
  "smell":["Flowers smell good.","꽃은 좋은 냄새가 나요.","'smell + 형용사'."],
  "taste":["This soup tastes great.","이 수프는 맛이 좋아요.","'taste + 형용사'."],
  "touch":["Don't touch the painting.","그림을 만지지 마요.","부정 명령문."],
  "wear":["I wear glasses.","나는 안경을 써요.","현재시제."],
  "carry":["Can you carry this bag?","이 가방 들어 줄래요?","'Can you ~?'."],
  "climb":["We climbed the mountain.","우리는 산을 올랐어요.","과거시제 climbed."],
  "dig":["The dog digs a hole.","개가 구멍을 파요.","3인칭 단수 digs."],
  "pick":["Pick a card.","카드 한 장을 골라요.","명령문."],
  "pour":["Pour the milk into the cup.","컵에 우유를 따라요.","'into the cup'."],
  "mix":["Mix the eggs and sugar.","달걀과 설탕을 섞어요.","and로 명사 연결."],
  "bake":["I love to bake cookies.","나는 쿠키 굽는 걸 좋아해요.","'love to + 동사원형'."],
  "boil":["Boil the water first.","먼저 물을 끓여요.","first는 부사(먼저)."],
  "fry":["Fry the eggs in oil.","기름에 달걀을 부쳐요.","'in oil'."],
  "peel":["Peel the banana.","바나나 껍질을 벗겨요.","명령문."],
  "slice":["Slice the bread thinly.","빵을 얇게 썰어요.","thinly는 부사(얇게)."],
  "build":["They build houses.","그들은 집을 지어요.","현재시제."],
  "break":["Don't break the glass.","유리를 깨지 마요.","부정 명령문."],
  "fix":["Can you fix my bike?","내 자전거 고쳐 줄래요?","'Can you ~?'."],
  "jog":["I jog every morning.","나는 매일 아침 조깅해요.","현재시제(습관)."],
  "roll":["The ball rolled down the hill.","공이 언덕 아래로 굴러갔어요.","과거시제 rolled."],
  "bounce":["The ball bounces high.","공이 높이 튀어요.","high는 부사."],
  "laugh":["We laughed a lot.","우리는 많이 웃었어요.","'a lot'은 많이."],
  "cry":["The baby is crying.","아기가 울고 있어요.","현재진행형."],
  "shout":["Don't shout at me.","나한테 소리치지 마요.","'shout at ~'은 ~에게 소리치다."],
  "whisper":["She whispered a secret.","그녀는 비밀을 속삭였어요.","과거시제 whispered."],
  "wake":["I wake up at seven.","나는 7시에 일어나요.","'wake up'은 일어나다."],
  "rest":["You should rest.","당신은 쉬어야 해요.","'should + 동사원형'."],
  "guess":["Guess what happened!","무슨 일이 있었는지 맞혀 봐요!","'guess what ~'."],
  "hope":["I hope you feel better.","나는 네가 낫기를 바라요.","'hope + 문장'."],
  "miss":["I miss my family.","나는 가족이 그리워요.","현재시제."],
  "care":["I care about you.","나는 너를 아껴요.","'care about ~'은 ~을 아끼다."],
  "shut":["Shut the door, please.","문을 닫아 주세요.","명령문."],
  "begin":["The class begins at nine.","수업은 9시에 시작해요.","3인칭 단수 begins."],
  "join":["Can I join you?","함께해도 될까요?","'Can I ~?'."],
  "share":["Let's share the pizza.","피자를 나눠 먹자.","'Let's + 동사원형'."],
  "lend":["Can you lend me a pen?","펜 좀 빌려줄래요?","'lend + 사람 + 사물'(4형식)."],
  "borrow":["May I borrow your book?","책 좀 빌려도 될까요?","'May I ~?'."],
  "save":["I save money every month.","나는 매달 돈을 모아요.","현재시제."],
  "spend":["I spend too much money.","나는 돈을 너무 많이 써요.","'too much'."],
  "lose":["Don't lose your ticket.","표를 잃어버리지 마요.","부정 명령문."],
  "visit":["We visit grandma on Sundays.","우리는 일요일마다 할머니를 찾아가요.","'on Sundays'는 일요일마다."],
  "leave":["The train leaves at noon.","기차는 정오에 떠나요.","3인칭 단수 leaves."],
  "return":["I will return soon.","나는 곧 돌아올게요.","'will + 동사원형'."],
  "arrive":["We arrived late.","우리는 늦게 도착했어요.","과거시제 arrived."],
  "enter":["Please enter the room quietly.","조용히 방에 들어가세요.","quietly는 부사."],
  "exit":["Use the back exit.","뒷문 출구를 이용해요.","exit는 출구·나가다."],
  "follow":["Follow me, please.","저를 따라오세요.","명령문."],
  "lead":["This road leads to the beach.","이 길은 해변으로 이어져요.","'lead to ~'는 ~로 이어지다."],
  "guide":["A guide showed us the way.","안내자가 우리에게 길을 알려줬어요.","과거시제 showed."],
  "choose":["Choose one, please.","하나를 골라 주세요.","명령문."],
  "agree":["I agree with you.","나는 당신 의견에 동의해요.","'agree with ~'은 ~에 동의하다."],
  "argue":["They often argue.","그들은 자주 다퉈요.","often은 빈도부사."],
  "fight":["Don't fight with your brother.","형이랑 싸우지 마요.","'fight with ~'은 ~와 싸우다."],
  "fail":["Don't be afraid to fail.","실패를 두려워하지 마요.","'be afraid to ~'."],
  "pass":["Pass me the salt, please.","소금 좀 건네주세요.","'pass + 사람 + 사물'(4형식)."],
  "hurt":["Did I hurt you?","제가 아프게 했나요?","과거 의문문 'Did ~?'."],
  "heal":["The wound will heal soon.","상처는 곧 나을 거예요.","'will + 동사원형'."],
  "feed":["I feed my cat twice a day.","나는 고양이에게 하루 두 번 먹이를 줘요.","'twice a day'."],
  "raise":["Raise your hand.","손을 들어요.","명령문."],
  "hide":["The kids hide behind the tree.","아이들이 나무 뒤에 숨어요.","'behind ~'은 ~뒤에."],
  "seek":["We seek the truth.","우리는 진실을 찾아요.","현재시제."],
  "chase":["The cat chases the mouse.","고양이가 쥐를 쫓아요.","3인칭 단수 chases."],
  "plant":["We plant trees in spring.","우리는 봄에 나무를 심어요.","'in spring'."],
  "sweep":["Sweep the floor.","바닥을 쓸어요.","명령문."],
  "knock":["Knock before you enter.","들어오기 전에 노크해요.","'before + 문장'."],
  "nod":["She nodded her head.","그녀는 고개를 끄덕였어요.","과거시제 nodded."],
  "bow":["The actors bowed to the crowd.","배우들이 관객에게 인사했어요.","과거시제 bowed."],
  "dive":["He dived into the pool.","그는 수영장에 뛰어들었어요.","'into the pool'."],
  "fold":["Fold the paper in half.","종이를 반으로 접어요.","'in half'."],
  "spin":["The top spins fast.","팽이가 빠르게 돌아요.","3인칭 단수 spins."],
  "shake":["Shake the bottle well.","병을 잘 흔들어요.","well은 부사."],
  "squeeze":["Squeeze the lemon.","레몬을 짜요.","명령문."],
  "stretch":["Stretch your arms.","팔을 쭉 펴요.","명령문."],
  "bend":["Bend your knees.","무릎을 구부려요.","명령문."],
  "lift":["Lift the box carefully.","상자를 조심히 들어요.","carefully는 부사."],
  "drag":["Don't drag the chair.","의자를 끌지 마요.","부정 명령문."],
  "toss":["Toss the ball to me.","공을 나에게 던져요.","'to me'."],
  "grab":["Grab my hand!","내 손을 잡아요!","명령문."],
  "pat":["She patted the dog gently.","그녀는 개를 부드럽게 토닥였어요.","gently는 부사."],
  "wipe":["Wipe the table.","탁자를 닦아요.","명령문."],
  "rub":["Rub your hands together.","손을 비벼요.","together는 부사."],
  "blow":["The wind blows hard.","바람이 세게 불어요.","hard는 부사."],
  "breathe":["Breathe deeply.","깊게 숨 쉬어요.","deeply는 부사(깊게)."],
  "yawn":["He yawned in class.","그는 수업 중에 하품했어요.","과거시제 yawned."],
  "sneeze":["I sneeze a lot in spring.","나는 봄에 재채기를 많이 해요.","'a lot'."],
  "cough":["She coughed all night.","그녀는 밤새 기침했어요.","'all night'은 밤새."],
  "bite":["The dog might bite.","그 개는 물지도 몰라요.","'might + 동사원형'은 ~할지도."],
  "chew":["Chew your food well.","음식을 잘 씹어요.","well은 부사."],
  "lick":["The cat licks its paws.","고양이가 발을 핥아요.","3인칭 단수 licks."],
  "swallow":["Swallow the pill with water.","약을 물과 함께 삼켜요.","'with water'."],
  "slip":["Be careful, the floor is slippery.","조심해요, 바닥이 미끄러워요.","slippery는 형용사."],
  "slide":["Kids slide down the hill.","아이들이 언덕을 미끄러져 내려가요.","'down the hill'."],
  "crawl":["The baby crawls on the floor.","아기가 바닥을 기어다녀요.","3인칭 단수 crawls."],
  "march":["The soldiers march together.","군인들이 함께 행진해요.","together는 부사."],
  "skip":["Don't skip breakfast.","아침을 거르지 마요.","skip은 거르다·건너뛰다."],
  "hop":["The rabbit hops away.","토끼가 깡충깡충 뛰어가요.","away는 부사(멀리)."],
  "stumble":["He stumbled over a rock.","그는 돌에 걸려 비틀거렸어요.","'over ~'는 ~에 걸려."],
  "wander":["We wandered around the city.","우리는 도시를 돌아다녔어요.","'around ~'은 ~주위를."],
  "rush":["Don't rush, take your time.","서두르지 말고 천천히 해요.","'take your time'은 천천히."],
  "hurry":["Hurry up, we are late!","서둘러요, 늦었어요!","'hurry up'은 서두르다."],
  "dash":["He dashed to the station.","그는 역으로 달려갔어요.","과거시제 dashed."],
  "drip":["The tap is dripping.","수도꼭지가 똑똑 떨어져요.","현재진행형."],
  "splash":["The kids splash in the pool.","아이들이 수영장에서 첨벙거려요.","'in the pool'."],
  "float":["Leaves float on the water.","잎이 물 위에 떠 있어요.","'on the water'."],
  "shine":["The sun shines brightly.","해가 밝게 빛나요.","brightly는 부사."],
  "glow":["The candle glows softly.","촛불이 부드럽게 빛나요.","softly는 부사."],
  "flash":["Lightning flashed in the sky.","번개가 하늘에서 번쩍였어요.","과거시제 flashed."],
  "sparkle":["The stars sparkle at night.","별이 밤에 반짝여요.","'at night'."],
  "freeze":["Water freezes at zero degrees.","물은 0도에서 얼어요.","현재시제(일반적 사실)."],
  "melt":["The ice is melting.","얼음이 녹고 있어요.","현재진행형."],
  "buzz":["Bees buzz around the flowers.","벌이 꽃 주위를 윙윙거려요.","'around ~'."],
  "hum":["She hums a song.","그녀는 노래를 흥얼거려요.","3인칭 단수 hums."],
  "cheer":["The crowd cheered loudly.","관중이 큰 소리로 환호했어요.","loudly는 부사."],
  "greet":["She greeted us warmly.","그녀는 우리를 따뜻하게 맞이했어요.","warmly는 부사."],
  "welcome":["Welcome to our home.","우리 집에 온 걸 환영해요.","'welcome to ~'."],
  "point":["Don't point at people.","사람을 손가락질하지 마요.","'point at ~'은 ~을 가리키다."],
  "aim":["Aim at the target.","과녁을 겨냥해요.","'aim at ~'은 ~을 겨누다."],
  "search":["I searched everywhere.","나는 어디든 찾아봤어요.","과거시제 searched."],
  "hunt":["Lions hunt at night.","사자는 밤에 사냥해요.","'at night'."],
  "gather":["We gathered around the fire.","우리는 불 주위에 모였어요.","과거시제 gathered."],
  "collect":["I collect old coins.","나는 옛날 동전을 모아요.","현재시제."],
  "pile":["He piled the books up.","그는 책을 쌓아 올렸어요.","'pile up'은 쌓아올리다."],
  "stack":["Stack the chairs neatly.","의자를 가지런히 쌓아요.","neatly는 부사."],
  "sort":["Sort the clothes by color.","옷을 색깔별로 분류해요.","'by color'는 색깔별로."],
  "weigh":["How much do you weigh?","몸무게가 얼마예요?","'how much ~'."],
  "print":["Print this page, please.","이 페이지를 출력해 주세요.","명령문."],
  "type":["I type fast.","나는 타자를 빨리 쳐요.","fast는 부사."],
  "click":["Click the button.","버튼을 클릭해요.","명령문."],
  "tap":["Tap the screen twice.","화면을 두 번 톡톡 쳐요.","twice는 두 번."],
  "sketch":["She sketched the scenery.","그녀는 경치를 스케치했어요.","과거시제 sketched."],
  "sew":["My mom sews my clothes.","우리 엄마가 내 옷을 꿰매요.","3인칭 단수 sews."],
  "knit":["Grandma knits warm socks.","할머니가 따뜻한 양말을 떠요.","3인칭 단수 knits."],
  "mow":["He mows the lawn on weekends.","그는 주말에 잔디를 깎아요.","'on weekends'."],
  "rake":["Rake the fallen leaves.","떨어진 낙엽을 긁어모아요.","fallen은 형용사(떨어진)."],
  "serve":["They serve breakfast at seven.","그들은 7시에 아침을 제공해요.","3인칭 복수 serve."],
  "pack":["Pack your bags.","짐을 싸요.","명령문."],
  "wrap":["Wrap the gift nicely.","선물을 예쁘게 포장해요.","nicely는 부사."],
  "mail":["I mailed the letter.","나는 편지를 부쳤어요.","과거시제 mailed."],
  "post":["She posted a photo online.","그녀는 온라인에 사진을 올렸어요.","과거시제 posted."],
  "invite":["I invited my friends.","나는 친구들을 초대했어요.","과거시제 invited."],
  "reply":["Please reply to my email.","제 이메일에 답장해 주세요.","'reply to ~'."],
  "solve":["Can you solve this puzzle?","이 퍼즐을 풀 수 있어요?","'Can you ~?'."],
  "spell":["How do you spell it?","그건 철자가 어떻게 되나요?","'how do you ~?'."],
  "erase":["Erase the wrong answer.","틀린 답을 지워요.","형용사 wrong."],
  "copy":["Copy this file, please.","이 파일을 복사해 주세요.","명령문."],
  "cancel":["I canceled the meeting.","나는 회의를 취소했어요.","과거시제 canceled."],
  "repeat":["Please repeat after me.","저를 따라 반복하세요.","'after me'."],
  "record":["He recorded the song.","그는 그 노래를 녹음했어요.","과거시제 recorded."],
  "whistle":["He whistled a tune.","그는 곡조를 휘파람으로 불었어요.","과거시제 whistled."],
  "stare":["Don't stare at strangers.","낯선 사람을 빤히 보지 마요.","'stare at ~'."],
  "glance":["She glanced at her watch.","그녀는 시계를 흘긋 봤어요.","'glance at ~'."],
  "kneel":["He knelt down to pray.","그는 기도하려고 무릎을 꿇었어요.","과거시제(kneel→knelt)."],
  "dodge":["He dodged the ball.","그는 공을 피했어요.","과거시제 dodged."],
  "pray":["They pray every morning.","그들은 매일 아침 기도해요.","현재시제(습관)."],
  "sick":["I feel sick today.","나는 오늘 몸이 안 좋아요.","'feel + 형용사'."],
  "thirsty":["I am so thirsty.","나는 너무 목말라요.","'so + 형용사'."],
  "sleepy":["I feel sleepy after lunch.","나는 점심 후에 졸려요.","'after lunch'."],
  "scared":["Are you scared of dogs?","개를 무서워해요?","'scared of ~'은 ~을 무서워하는."],
  "afraid":["Don't be afraid.","무서워하지 마요.","'be afraid'."],
  "surprised":["I was surprised by the news.","나는 그 소식에 놀랐어요.","'surprised by ~'."],
  "bored":["The kids are bored.","아이들이 지루해해요.","'be + 형용사'."],
  "excited":["I am excited about the trip.","나는 여행이 기대돼요.","'excited about ~'."],
  "nervous":["She felt nervous before the test.","그녀는 시험 전에 긴장했어요.","과거시제(feel→felt)."],
  "lonely":["He feels lonely sometimes.","그는 가끔 외로워해요.","sometimes는 가끔."],
  "jealous":["Don't be jealous.","질투하지 마요.","'be + 형용사'."],
  "funny":["That joke is so funny.","그 농담은 정말 웃겨요.","'so + 형용사'."],
  "silly":["Don't be silly.","바보같이 굴지 마요.","'be + 형용사'."],
  "crazy":["This idea sounds crazy.","이 생각은 미친 소리 같아요.","'sound + 형용사'."],
  "smart":["She is a smart student.","그녀는 똑똑한 학생이에요.","형용사 smart."],
  "clever":["What a clever dog!","정말 영리한 개다!","감탄문."],
  "stupid":["That was a stupid mistake.","그건 멍청한 실수였어요.","과거시제(was)."],
  "foolish":["It was a foolish choice.","그건 어리석은 선택이었어요.","과거시제(was)."],
  "weak":["I feel weak today.","나는 오늘 기운이 없어요.","'feel + 형용사'."],
  "healthy":["Eat healthy food.","건강한 음식을 먹어요.","형용사 healthy."],
  "ill":["She is seriously ill.","그녀는 심하게 아파요.","seriously는 부사."],
  "neat":["Keep your desk neat.","책상을 깔끔하게 유지해요.","'keep + 목적어 + 형용사'."],
  "messy":["My room is so messy.","내 방은 너무 지저분해요.","'so + 형용사'."],
  "ugly":["The building is ugly.","그 건물은 못생겼어요.","'be + 형용사'."],
  "cute":["The puppy is so cute.","강아지가 너무 귀여워요.","'so + 형용사'."],
  "lovely":["What a lovely day!","정말 사랑스러운 날이야!","감탄문."],
  "handsome":["He is a handsome man.","그는 잘생긴 남자예요.","형용사 handsome."],
  "wealthy":["They are a wealthy family.","그들은 부유한 가족이에요.","형용사 wealthy."],
  "cheap":["These shoes are cheap.","이 신발은 싸요.","복수 주어라 are."],
  "quick":["Take a quick look.","빠르게 한번 봐요.","형용사 quick."],
  "early":["I get up early.","나는 일찍 일어나요.","early는 부사(일찍)."],
  "late":["Don't be late.","늦지 마요.","'be + 형용사'."],
  "near":["The store is near.","가게가 가까워요.","'be + 형용사'."],
  "far":["The school is far from here.","학교는 여기서 멀어요.","'far from ~'은 ~에서 먼."],
  "high":["The mountain is very high.","산이 매우 높아요.","'be + 형용사'."],
  "low":["The chair is too low.","의자가 너무 낮아요.","'too + 형용사'."],
  "cool":["The breeze feels cool.","산들바람이 시원해요.","'feel + 형용사'."],
  "freezing":["It is freezing outside.","밖이 꽁꽁 얼 만큼 추워요.","비인칭 주어 it."],
  "dim":["The light is dim.","불빛이 어둑해요.","'be + 형용사'."],
  "silent":["The room was silent.","방이 조용했어요.","과거시제(was)."],
  "simple":["The recipe is simple.","조리법이 간단해요.","'be + 형용사'."],
  "closed":["The shop is closed.","가게가 닫혀 있어요.","'be + 형용사'."],
  "glad":["I am glad to see you.","만나서 반가워요.","'glad to + 동사원형'."],
  "mad":["She is mad at me.","그녀는 나에게 화났어요.","'mad at ~'은 ~에게 화난."],
  "upset":["He is upset about it.","그는 그 일로 속상해해요.","'upset about ~'."],
  "mean":["Don't be mean to others.","남에게 못되게 굴지 마요.","'mean to ~'."],
  "cruel":["That was a cruel thing to say.","그건 잔인한 말이었어요.","과거시제(was)."],
  "gentle":["Be gentle with the baby.","아기를 부드럽게 다뤄요.","'gentle with ~'."],
  "polite":["She is always polite.","그녀는 항상 예의 발라요.","always는 항상."],
  "rude":["It is rude to interrupt.","끼어드는 건 무례해요.","'It is + 형용사 + to ~'."],
  "honest":["Please be honest with me.","나에게 솔직해 주세요.","'honest with ~'."],
  "false":["That statement is false.","그 말은 거짓이에요.","'be + 형용사'."],
  "fake":["This is a fake watch.","이건 가짜 시계예요.","형용사 fake."],
  "correct":["Your answer is correct.","당신의 답이 맞아요.","'be + 형용사'."],
  "wrong":["Something is wrong.","뭔가 잘못됐어요.","something은 단수 취급."],
  "great":["You did a great job.","당신은 훌륭하게 해냈어요.","형용사 great."],
  "awful":["The weather is awful today.","오늘 날씨가 끔찍해요.","'be + 형용사'."],
  "purple":["She wore a purple dress.","그녀는 보라색 드레스를 입었어요.","과거시제(wear→wore)."],
  "violet":["Violet is a shade of purple.","바이올렛은 보라색 계열이에요.","'a shade of ~'."],
  "sunny":["It is sunny today.","오늘은 화창해요.","비인칭 주어 it(날씨)."],
  "rainy":["It is a rainy day.","비 오는 날이에요.","형용사 rainy."],
  "cloudy":["The sky is cloudy.","하늘이 흐려요.","'be + 형용사'."],
  "windy":["It is windy outside.","밖에 바람이 불어요.","비인칭 주어 it."],
  "snowy":["We had a snowy winter.","우리는 눈 많은 겨울을 보냈어요.","형용사 snowy."],
  "stormy":["It was a stormy night.","폭풍우 치는 밤이었어요.","과거시제(was)."],
  "bitter":["This coffee is bitter.","이 커피는 써요.","'be + 형용사'."],
  "sticky":["My hands are sticky.","손이 끈적해요.","복수 주어라 are."],
  "fluffy":["The cat has fluffy fur.","고양이는 푹신한 털을 가졌어요.","형용사 fluffy."],
  "shiny":["The car is shiny.","차가 반짝여요.","'be + 형용사'."],
  "smooth":["Her skin is smooth.","그녀의 피부는 매끄러워요.","'be + 형용사'."],
  "rough":["The road is rough.","길이 울퉁불퉁해요.","'be + 형용사'."],
  "straight":["Draw a straight line.","직선을 그어요.","형용사 straight."],
  "curly":["She has curly hair.","그녀는 곱슬머리예요.","형용사 curly."],
  "square":["The table is square.","탁자가 네모나요.","'be + 형용사'."],
  "giant":["A giant tree stood there.","거대한 나무가 거기 서 있었어요.","과거시제(stand→stood)."],
  "tasty":["This food is tasty.","이 음식은 맛있어요.","'be + 형용사'."],
  "juicy":["The orange is juicy.","오렌지가 즙이 많아요.","'be + 형용사'."],
  "famous":["She is a famous singer.","그녀는 유명한 가수예요.","형용사 famous."],
  "wild":["Wild animals live here.","야생 동물이 여기 살아요.","형용사 wild."],
  "tame":["The horse is tame.","그 말은 길들여졌어요.","'be + 형용사'."],
  "loose":["This shirt is too loose.","이 셔츠는 너무 헐렁해요.","'too + 형용사'."],
  "tight":["These jeans are too tight.","이 청바지는 너무 꽉 껴요.","복수 주어라 are."],
  "blunt":["This knife is blunt.","이 칼은 무뎌요.","'be + 형용사'."],
  "dull":["The movie was dull.","그 영화는 지루했어요.","과거시제(was)."],
  "fancy":["We ate at a fancy restaurant.","우리는 고급 식당에서 먹었어요.","형용사 fancy."],
  "plain":["I like plain rice.","나는 흰밥을 좋아해요.","형용사 plain(무미한·소박한)."],
  "asleep":["The baby is asleep.","아기가 잠들어 있어요.","'be + 형용사'."],
  "awake":["Are you still awake?","아직 깨어 있어요?","still은 아직."],
  "alive":["The fish is still alive.","그 물고기는 아직 살아 있어요.","'be + 형용사'."],
  "dead":["The plant is dead.","그 식물은 죽었어요.","'be + 형용사'."],
  "alone":["I live alone.","나는 혼자 살아요.","alone은 형용사·부사(혼자)."],
  "deaf":["He is deaf in one ear.","그는 한쪽 귀가 안 들려요.","'in one ear'."],
  "blind":["The old man is blind.","그 노인은 앞을 못 봐요.","'be + 형용사'."],
  "brief":["Keep it brief.","간단하게 해요.","'keep + 목적어 + 형용사'."],
  "spare":["Do you have a spare key?","여분의 열쇠가 있어요?","형용사 spare."],
  "extra":["I need an extra chair.","의자가 하나 더 필요해요.","형용사 extra."],
  "exact":["Tell me the exact time.","정확한 시간을 알려줘요.","형용사 exact."],
  "total":["The total cost is high.","총비용이 높아요.","형용사 total."],
  "whole":["I ate the whole pizza.","나는 피자 한 판을 다 먹었어요.","'the whole ~'은 ~전체."],
  "main":["What is the main reason?","주된 이유가 뭐예요?","형용사 main."],
  "final":["This is your final chance.","이게 마지막 기회예요.","형용사 final."],
  "ready":["Are you ready to go?","갈 준비됐어요?","'ready to + 동사원형'."],
  "usual":["I sat in my usual seat.","나는 늘 앉던 자리에 앉았어요.","형용사 usual."],
  "normal":["It is normal to feel tired.","피곤한 건 정상이에요.","'It is + 형용사 + to ~'."],
  "strange":["I heard a strange sound.","나는 이상한 소리를 들었어요.","과거시제(hear→heard)."],
  "odd":["That is an odd habit.","그건 이상한 버릇이에요.","형용사 odd."],
  "weird":["This tastes weird.","이거 이상한 맛이 나요.","'taste + 형용사'."],
  "equal":["Cut it into equal parts.","그것을 똑같은 크기로 잘라요.","형용사 equal."],
  "double":["I want a double cheeseburger.","나는 더블 치즈버거를 원해요.","형용사 double."],
  "single":["Not a single person came.","단 한 사람도 안 왔어요.","'not a single ~'은 단 하나도 없는."],
  "narrow":["The path is narrow.","길이 좁아요.","'be + 형용사'."],
  "shallow":["The pool is shallow here.","이쪽 수영장은 얕아요.","'be + 형용사'."],
  "steep":["The hill is very steep.","언덕이 매우 가팔라요.","'be + 형용사'."],
  "steady":["Keep a steady pace.","꾸준한 속도를 유지해요.","형용사 steady."],
  "solid":["The ground is solid.","땅이 단단해요.","'be + 형용사'."],
  "hollow":["The tree is hollow inside.","그 나무는 속이 비어 있어요.","inside는 부사."],
  "rotten":["The egg is rotten.","그 달걀은 썩었어요.","'be + 형용사'."],
  "ripe":["The banana is ripe now.","바나나가 이제 익었어요.","'be + 형용사'."],
  "raw":["I don't eat raw fish.","나는 날생선을 안 먹어요.","형용사 raw."],
  "gorgeous":["You look gorgeous tonight.","오늘 밤 정말 멋져 보여요.","'look + 형용사'."],
  "pale":["You look pale. Are you okay?","창백해 보여요. 괜찮아요?","'look + 형용사'."],
  "chubby":["The baby has chubby cheeks.","아기는 통통한 볼을 가졌어요.","형용사 chubby."],
  "skinny":["He is very skinny.","그는 매우 말랐어요.","'be + 형용사'."],
  "bald":["My grandfather is bald.","우리 할아버지는 대머리예요.","'be + 형용사'."],
  "elderly":["She helps elderly people.","그녀는 노인들을 도와요.","형용사 elderly."],
  "mature":["He is mature for his age.","그는 나이에 비해 성숙해요.","'for his age'."],
  "brilliant":["That is a brilliant idea.","그건 뛰어난 생각이에요.","형용사 brilliant."],
  "massive":["It was a massive building.","그건 거대한 건물이었어요.","과거시제(was)."],
  "chilly":["It is chilly this morning.","오늘 아침은 쌀쌀해요.","비인칭 주어 it."],
  "damp":["The towel is still damp.","수건이 아직 축축해요.","still은 아직."],
  "muddy":["My shoes are muddy.","내 신발이 진흙투성이예요.","복수 주어라 are."],
  "dusty":["The shelf is dusty.","선반이 먼지투성이예요.","'be + 형용사'."],
  "foggy":["It is foggy outside.","밖이 안개가 꼈어요.","비인칭 주어 it."],
  "icy":["The road is icy.","길이 빙판이에요.","'be + 형용사'."],
  "furry":["I have a furry cat.","나는 털복숭이 고양이가 있어요.","형용사 furry."],
  "hairy":["He has hairy arms.","그는 팔에 털이 많아요.","형용사 hairy."],
  "slimy":["The frog feels slimy.","개구리는 미끈거려요.","'feel + 형용사'."],
  "breakfast":["I eat breakfast at seven.","나는 7시에 아침을 먹어요.","'eat breakfast'(무관사)."],
  "lunch":["Let's have lunch together.","같이 점심 먹자.","'have lunch'."],
  "class":["My English class is fun.","내 영어 수업은 재미있어요.","'be + 형용사'."],
  "lesson":["Today's lesson is hard.","오늘 수업은 어려워요.","'be + 형용사'."],
  "test":["I have a math test tomorrow.","나는 내일 수학 시험이 있어요.","tomorrow는 내일."],
  "grade":["She got a good grade.","그녀는 좋은 성적을 받았어요.","과거시제(get→got)."],
  "homework":["I finished my homework.","나는 숙제를 끝냈어요.","과거시제 finished."],
  "eraser":["May I borrow your eraser?","지우개 좀 빌려도 될까요?","'May I ~?'."],
  "ruler":["Use a ruler to draw a line.","자로 선을 그어요.","'use A to ~'."],
  "paper":["Write it on a piece of paper.","종이 한 장에 적어요.","'a piece of paper'."],
  "crayon":["The child drew with crayons.","아이가 크레용으로 그렸어요.","과거시제(draw→drew)."],
  "marker":["Write it with a black marker.","검은 마커로 적어요.","'with a marker'."],
  "classroom":["The classroom is empty.","교실이 비어 있어요.","'be + 형용사'."],
  "playground":["Kids play on the playground.","아이들이 놀이터에서 놀아요.","'on the playground'."],
  "weekend":["What are your weekend plans?","주말 계획이 뭐예요?","형용사처럼 쓰인 weekend."],
  "today":["What day is it today?","오늘이 무슨 요일이에요?","'what day ~'."],
  "tomorrow":["See you tomorrow.","내일 봐요.","tomorrow는 부사·명사."],
  "yesterday":["I met him yesterday.","나는 어제 그를 만났어요.","과거시제(meet→met)."],
  "hour":["The trip takes an hour.","그 여행은 한 시간 걸려요.","'take + 시간'은 ~걸리다."],
  "minute":["Wait a minute, please.","잠깐만 기다려 주세요.","'a minute'은 잠깐."],
  "spring":["Flowers bloom in spring.","봄에 꽃이 피어요.","'in spring'."],
  "autumn":["Leaves fall in autumn.","가을에 잎이 떨어져요.","'in autumn'."],
  "moment":["Wait a moment, please.","잠시만 기다려 주세요.","'a moment'은 잠시."],
  "midnight":["The clock struck midnight.","시계가 자정을 알렸어요.","과거시제(strike→struck)."],
  "birthday":["Happy birthday to you!","생일 축하해요!","'Happy birthday'."],
  "party":["We had a birthday party.","우리는 생일 파티를 열었어요.","과거시제(have→had)."],
  "doctor":["You should see a doctor.","병원에 가 봐야 해요.","'see a doctor'는 진찰받다."],
  "police":["Call the police!","경찰을 불러요!","police는 복수 취급."],
  "pilot":["He wants to be a pilot.","그는 조종사가 되고 싶어 해요.","'want to be ~'."],
  "driver":["The bus driver was kind.","버스 기사가 친절했어요.","과거시제(was)."],
  "singer":["She is a famous singer.","그녀는 유명한 가수예요.","형용사 famous."],
  "dancer":["She is a ballet dancer.","그녀는 발레 무용수예요.","형용사처럼 쓰인 ballet."],
  "painter":["The painter sold his art.","그 화가는 자기 그림을 팔았어요.","과거시제(sell→sold)."],
  "writer":["He is a famous writer.","그는 유명한 작가예요.","형용사 famous."],
  "actor":["My favorite actor won an award.","내가 좋아하는 배우가 상을 받았어요.","과거시제(win→won)."],
  "baker":["The baker makes fresh bread.","제빵사가 갓 구운 빵을 만들어요.","3인칭 단수 makes."],
  "farmer":["The farmer grows rice.","농부가 쌀을 길러요.","3인칭 단수 grows."],
  "chef":["The chef cooked a great meal.","주방장이 훌륭한 식사를 만들었어요.","과거시제 cooked."],
  "judge":["The judge made a decision.","판사가 결정을 내렸어요.","과거시제(make→made)."],
  "lawyer":["She works as a lawyer.","그녀는 변호사로 일해요.","'work as ~'은 ~로 일하다."],
  "scientist":["The scientist did an experiment.","과학자가 실험을 했어요.","과거시제(do→did)."],
  "artist":["He is a talented artist.","그는 재능 있는 예술가예요.","형용사 talented."],
  "soldier":["The soldier is very brave.","그 군인은 매우 용감해요.","'be + 형용사'."],
  "sailor":["The sailor works on a ship.","선원은 배에서 일해요.","'on a ship'."],
  "captain":["The captain steers the ship.","선장이 배를 조종해요.","3인칭 단수 steers."],
  "guard":["A guard stands at the gate.","경비원이 문에 서 있어요.","3인칭 단수 stands."],
  "clerk":["The clerk helped me.","점원이 나를 도와줬어요.","과거시제 helped."],
  "waiter":["The waiter brought our food.","종업원이 우리 음식을 가져왔어요.","과거시제(bring→brought)."],
  "soccer":["We play soccer after school.","우리는 방과 후에 축구를 해요.","'after school'."],
  "baseball":["Baseball is popular here.","야구는 여기서 인기 있어요.","'be + 형용사'."],
  "tennis":["Let's play tennis.","테니스 치자.","'play tennis'."],
  "golf":["My dad plays golf on Sundays.","우리 아빠는 일요일마다 골프를 쳐요.","'on Sundays'."],
  "sport":["What is your favorite sport?","가장 좋아하는 운동이 뭐예요?","favorite은 가장 좋아하는."],
  "race":["He won the race.","그는 경주에서 이겼어요.","과거시제(win→won)."],
  "match":["The match starts at three.","경기는 3시에 시작해요.","3인칭 단수 starts."],
  "goal":["He scored a goal.","그는 골을 넣었어요.","과거시제 scored."],
  "score":["The final score was 2 to 1.","최종 점수는 2 대 1이었어요.","'A to B'는 A 대 B."],
  "coach":["The coach trained the team.","코치가 팀을 훈련시켰어요.","과거시제 trained."],
  "player":["He is the best player.","그는 최고의 선수예요.","최상급 best."],
  "swimming":["Swimming is good exercise.","수영은 좋은 운동이에요.","동명사 주어."],
  "running":["Running keeps me healthy.","달리기는 나를 건강하게 해 줘요.","동명사 주어."],
  "piano":["She plays the piano well.","그녀는 피아노를 잘 쳐요.","악기 앞 the."],
  "guitar":["He plays the guitar.","그는 기타를 쳐요.","악기 앞 the."],
  "violin":["I am learning the violin.","나는 바이올린을 배우고 있어요.","현재진행형."],
  "trumpet":["He plays the trumpet loudly.","그는 트럼펫을 크게 불어요.","loudly는 부사."],
  "band":["My brother is in a band.","우리 형은 밴드에 있어요.","'in a band'."],
  "stage":["The singer is on the stage.","가수가 무대 위에 있어요.","'on the stage'."],
  "movie":["Let's watch a movie.","영화 보자.","'watch a movie'."],
  "eleven":["The game starts at eleven.","경기는 11시에 시작해요.","'at eleven'."],
  "twelve":["A year has twelve months.","일 년은 열두 달이에요.","수 twelve."],
  "twenty":["There are twenty students.","학생이 스무 명 있어요.","'There are + 복수'."],
  "thirty":["He is thirty years old.","그는 서른 살이에요.","'~ years old'."],
  "forty":["My mom is forty.","우리 엄마는 마흔이에요.","나이 표현."],
  "fifty":["The book costs fifty dollars.","그 책은 50달러예요.","3인칭 단수 costs."],
  "hundred":["There were a hundred people.","백 명이 있었어요.","과거시제(were)."],
  "thousand":["It costs a thousand won.","그것은 천 원이에요.","3인칭 단수 costs."],
  "half":["I ate half of the cake.","나는 케이크의 반을 먹었어요.","'half of ~'은 ~의 절반."],
  "dozen":["I bought a dozen eggs.","나는 달걀 한 다스를 샀어요.","'a dozen'은 12개."],
  "bedroom":["My bedroom is upstairs.","내 침실은 위층에 있어요.","upstairs는 부사."],
  "bathroom":["Where is the bathroom?","화장실이 어디예요?","'where is ~?'."],
  "garage":["The car is in the garage.","차가 차고에 있어요.","'in the garage'."],
  "hall":["Walk down the hall.","복도를 따라 걸어가요.","'down the hall'."],
  "attic":["We keep boxes in the attic.","우리는 다락방에 상자를 보관해요.","'in the attic'."],
  "basement":["The laundry is in the basement.","세탁실은 지하실에 있어요.","'in the basement'."],
  "fence":["The dog jumped over the fence.","개가 울타리를 뛰어넘었어요.","'over the fence'."],
  "phone":["My phone is dead.","내 전화기 배터리가 다 됐어요.","dead는 방전된."],
  "camera":["She bought a new camera.","그녀는 새 카메라를 샀어요.","과거시제 bought."],
  "radio":["I listen to the radio.","나는 라디오를 들어요.","'listen to ~'."],
  "computer":["My computer is slow.","내 컴퓨터가 느려요.","'be + 형용사'."],
  "screen":["Don't touch the screen.","화면을 만지지 마요.","부정 명령문."],
  "dollar":["It costs five dollars.","그것은 5달러예요.","복수 dollars."],
  "cent":["This costs fifty cents.","이것은 50센트예요.","복수 cents."],
  "price":["The price is too high.","가격이 너무 비싸요.","'too + 형용사'."],
  "trip":["Have a nice trip!","좋은 여행 되세요!","형용사 nice."],
  "menu":["Can I see the menu?","메뉴 좀 볼 수 있어요?","'Can I ~?'."],
  "recipe":["She shared her recipe.","그녀는 자기 조리법을 공유했어요.","과거시제 shared."],
  "dessert":["What's for dessert?","후식은 뭐예요?","'what's for ~?'."],
  "sandwich":["I made a ham sandwich.","나는 햄 샌드위치를 만들었어요.","과거시제(make→made)."],
  "pizza":["Let's order pizza.","피자 시키자.","'order pizza'."],
  "parent":["My parents love me.","우리 부모님은 나를 사랑해요.","복수 parents."],
  "anger":["He couldn't hide his anger.","그는 화를 숨기지 못했어요.","과거 부정(couldn't)."],
  "joy":["The news brought us joy.","그 소식은 우리에게 기쁨을 줬어요.","과거시제(bring→brought)."],
  "fear":["She has a fear of heights.","그녀는 고소공포증이 있어요.","'a fear of ~'."],
  "space":["There is no space left.","남은 공간이 없어요.","'no space'."],
  "energy":["I have no energy today.","나는 오늘 기운이 없어요.","'no energy'."],
  "power":["Knowledge is power.","아는 것이 힘이에요.","명언."],
  "sound":["I heard a strange sound.","나는 이상한 소리를 들었어요.","과거시제(hear→heard)."],
  "voice":["She has a beautiful voice.","그녀는 아름다운 목소리를 가졌어요.","형용사 beautiful."],
  "noise":["Please don't make noise.","소음을 내지 마세요.","'make noise'."],
  "silence":["There was a long silence.","긴 침묵이 있었어요.","과거시제(was)."],
  "shape":["The cloud has a funny shape.","구름이 우스운 모양이에요.","형용사 funny."],
  "size":["What size do you wear?","어떤 사이즈를 입으세요?","'what size ~?'."],
  "weight":["What is your weight?","몸무게가 얼마예요?","'what is ~?'."],
  "length":["Measure the length of the table.","탁자의 길이를 재요.","'the length of ~'."],
  "height":["What is your height?","키가 얼마예요?","'what is ~?'."],
  "speed":["Reduce your speed.","속도를 줄여요.","명령문."],
  "distance":["The distance is too far.","거리가 너무 멀어요.","'too + 형용사'."],
  "corner":["The shop is on the corner.","가게는 모퉁이에 있어요.","'on the corner'."],
  "center":["Stand in the center.","가운데에 서요.","'in the center'."],
  "side":["Sit by my side.","내 옆에 앉아요.","'by my side'는 내 옆에."],
  "top":["The cat is on top of the box.","고양이가 상자 위에 있어요.","'on top of ~'."],
  "bottom":["The keys are at the bottom of the bag.","열쇠가 가방 바닥에 있어요.","'at the bottom of ~'."],
  "middle":["He sat in the middle.","그는 가운데에 앉았어요.","'in the middle'."],
  "nature":["I love walking in nature.","나는 자연 속을 걷는 걸 좋아해요.","'in nature'."],
  "lucky":["You are so lucky!","정말 운이 좋네요!","'so + 형용사'."],
  "careful":["Be careful on the stairs.","계단에서 조심해요.","'be + 형용사'."],
  "careless":["That was a careless mistake.","그건 부주의한 실수였어요.","과거시제(was)."],
  "helpful":["Your advice was helpful.","당신의 조언이 도움이 됐어요.","과거시제(was)."],
  "useful":["This app is very useful.","이 앱은 매우 유용해요.","'be + 형용사'."],
  "useless":["This old phone is useless.","이 낡은 전화기는 쓸모없어요.","'be + 형용사'."],
  "harmful":["Smoking is harmful to health.","흡연은 건강에 해로워요.","'harmful to ~'."],
  "painful":["The injection was painful.","그 주사는 아팠어요.","과거시제(was)."],
  "cheerful":["She is always cheerful.","그녀는 항상 쾌활해요.","always는 항상."],
  "peaceful":["The village is peaceful.","그 마을은 평화로워요.","'be + 형용사'."],
  "colorful":["The garden is colorful.","정원이 알록달록해요.","'be + 형용사'."],
  "powerful":["He gave a powerful speech.","그는 강력한 연설을 했어요.","과거시제(give→gave)."],
  "thankful":["I am thankful for your help.","당신의 도움에 감사해요.","'thankful for ~'."],
  "hopeful":["We are hopeful about the future.","우리는 미래에 대해 희망적이에요.","'hopeful about ~'."],
  "joyful":["It was a joyful day.","즐거운 하루였어요.","과거시제(was)."],
  "playful":["The kitten is playful.","새끼고양이가 장난기가 많아요.","'be + 형용사'."],
  "restful":["The vacation was restful.","그 휴가는 편안했어요.","과거시제(was)."],
  "fearful":["She gave a fearful look.","그녀는 두려운 표정을 지었어요.","과거시제(give→gave)."],
  "graceful":["The dancer is graceful.","그 무용수는 우아해요.","'be + 형용사'."],
  "skillful":["He is a skillful driver.","그는 능숙한 운전자예요.","형용사 skillful."]
};
